In [1]:
import csv
import pandas as pd
import sys

RESULTS_FILE_CSV_DIALECT = csv.excel_tab
# NOTE: "category" dtype doesn't work with pandas-0.21.0 but does with pandas-0.21.1
__RESULTS_FILE_DTYPES = {"DYAD": "category", "WORD": "category", "IS_TARGET": bool, "IS_OOV": bool,
				 "IS_INSTRUCTOR": bool, "SHAPE": "category", "ONLY_INSTRUCTOR": bool, "WEIGHT_BY_FREQ": bool}

def read_results_file(inpath: str, encoding: str) -> pd.DataFrame:
	print("Reading \"{}\" using encoding \"{}\".".format(inpath, encoding), file=sys.stderr)
	result = pd.read_csv(inpath, dialect=RESULTS_FILE_CSV_DIALECT, sep=RESULTS_FILE_CSV_DIALECT.delimiter,
						 float_precision="round_trip",
						 encoding=encoding, memory_map=True, dtype=__RESULTS_FILE_DTYPES)
	return result

infile_path = r"D:\Users\tcshore\Downloads\wordscores.tsv"
cv_results = read_results_file(infile_path, "windows-1252")

Reading "D:\Users\tcshore\Downloads\wordscores.tsv" using encoding "windows-1252".


In [2]:
dyad_ids = tuple(sorted(frozenset(cv_results["DYAD"].unique())))
print("Read {} cross-validation results for {} dyad(s).".format(cv_results.shape[0], len(dyad_ids)),
      file=sys.stderr)
entity_ids = frozenset(cv_results["ENTITY"].unique())
print("Found {} unique entity IDs.".format(len(entity_ids)), file=sys.stderr)

Read 1206840 cross-validation results for 39 dyad(s).
Found 20 unique entity IDs.


In [3]:
def are_all_entities_represented(df: pd.DataFrame, entity_ids) -> bool:
	"""
	Checks if all entities are represented for each individual token in each utterance in the dataframe.
    
	:param df: The dataframe to check.
	:param entity_ids: A collection of all unique entity IDs.
	:return: true iff for each token in each utterance there is one row for each entity ID.
	"""
	utt_toks = df.groupby(
		("CROSS_VALIDATION_ITER", "DYAD", "ROUND", "UTT_START_TIME", "UTT_END_TIME", "WORD", "TOKEN_SEQ_ORDINALITY"), as_index=False)
	print("Found {} utterance tokens for all cross-validations.".format(len(utt_toks)), file=sys.stderr)
	# Check if there is a row for each entity (possible referent) for each token
	return all(utt_toks.apply(lambda group: is_collection_equivalent(group["ENTITY"], entity_ids)))

def is_collection_equivalent(c1, c2) -> bool:
	c1_len = len(c1)
	c2_len = len(c2)
	return c1_len == c2_len and all(elem in c2 for elem in c1)

assert are_all_entities_represented(cv_results, entity_ids)

Found 60342 utterance tokens for all cross-validations.


In [4]:
def find_target_ref_rows(df: pd.DataFrame) -> pd.DataFrame:
    result = df.loc[df["IS_TARGET"] == True]
    result_row_count = result.shape[0]
    complement_row_count = df.loc[~df.index.isin(result.index)].shape[0]
    assert result_row_count + complement_row_count == df.shape[0]
    print("Found {} nontarget rows and {} target rows. Ratio: {}".format(result_row_count, complement_row_count, complement_row_count / float(result_row_count)), file=sys.stderr)
    return result

cv_results = find_target_ref_rows(cv_results)

Found 60342 nontarget rows and 1146498 target rows. Ratio: 19.0


In [57]:
import math
from typing import List, Tuple

import keras.preprocessing.sequence
import numpy as np
from sklearn.preprocessing import OneHotEncoder

class TokenSequenceFactory(object):

	def __init__(self, max_len: int):
		self.__max_len = max_len
		self.__max_len_divisor = float(max_len)

	def __call__(self, df: pd.DataFrame) -> Tuple[List[np.array], List[np.array]]:
		"""
		Creates a sequence of sequences of tokens, each representing an utterance, each of which thus causes an "interruption" in the chain
		so that e.g. the first token of one utterance is not learned as dependent on the last token of the utterance preceding it.
		:param df: The DataFrame to process.
		:return: Paired lists of 2D numpy arrays, each representing a sequence of datapoints which represents an utterance and the corresponding scores to predict.
		"""
        # https://stackoverflow.com/a/47815400/1391325
		df.sort_values("TOKEN_SEQ_ORDINALITY", inplace=True)
		sequences = df.groupby(("CROSS_VALIDATION_ITER", "DYAD", "ROUND", "UTT_START_TIME", "UTT_END_TIME", "ENTITY"),
							   as_index=False)
		#sequences.apply(lambda seq : self.create_word_forms(seq["ONEHOT_WORD_LABEL"].values))
        
		word_seqs = []
		score_seqs = []
		max_len_divisor = float(self.__max_len)
		split_seq_scores = sequences.apply(self.__split_row_values)
		for word_seq, score_seq in split_seq_scores:
			word_seqs.extend(word_seq)
			score_seqs.extend(score_seq)
		assert max(len(seq) for seq in word_seqs) <= self.__max_len
		return word_seqs, score_seqs

	def __split_row_values(self, df: pd.DataFrame) -> Tuple[np.array, np.array]:
		seq_words = df["WORD"].values
		seq_scores = df["PROBABILITY"].values
        
		partition_count = math.ceil(len(seq_words) / self.__max_len_divisor)
		split_seq_words = np.array_split(seq_words, partition_count)
		split_seq_scores = np.array_split(seq_scores, partition_count)
		return split_seq_words, split_seq_scores

desired_seq_len = 4
print("Splitting token sequences.", file=sys.stderr)
token_seq_factory = TokenSequenceFactory(desired_seq_len)
word_seqs, score_seqs = token_seq_factory(cv_results)
print("Split data into {} token sequences with a maximum sequence length of {}.".format(len(word_seqs),
                                                                                        desired_seq_len),
      file=sys.stderr)

Splitting token sequences.
Split data into 20740 token sequences with a maximum sequence length of 4.


In [64]:
from typing import Sequence

def pad_sequence(word_score_seq: Tuple[np.array, np.array], min_length: int) -> Tuple[np.array, np.array]:
	word_seq, score_seq = word_score_seq
	word_count = len(word_seq)
	assert word_count == len(score_seq)
	length_diff = min_length - word_count
	if length_diff > 0:
		# NOTE: creating an intermediate tuple is necessary
		padding_words = np.full(length_diff, "__PADDING__")
		padded_word_seq = np.concatenate((padding_words, word_seq), axis=0)
		assert len(padded_word_seq) == min_length
		padding_scores = np.full(length_diff, 0.0)
		padded_score_seq = np.concatenate((padding_scores, score_seq), axis=0)
		assert len(padded_score_seq) == min_length
		result = padded_word_seq, padded_score_seq
	else:
		result = word_seq, score_seq

	return result

def pad_sequences(word_score_seqs : Sequence[Tuple[np.array, np.array]], min_length: int):
    for word_score_seq in word_score_seqs:
        print(pad_sequence(word_score_seq, min_length))

            
pad_sequences(zip(word_seqs, score_seqs), desired_seq_len)

(array(['ah', 'okay', 'now', 'I'], dtype=object), array([ 0.60987518,  0.51752287,  0.44109063,  0.47596564]))
(array(['see', 'a', 'selected', 'piece'], dtype=object), array([ 0.49421434,  0.45865621,  0.12580566,  0.46943467]))
(array(['__PADDING__', '__PADDING__', 'all', 'right'], dtype=object), array([ 0.       ,  0.       ,  0.3956217,  0.3559954]))
(array(['waiting', 'for', 'other', 'player'], dtype=object), array([  4.48115780e-16,   4.28518916e-01,   5.58960072e-01,
         1.83746008e-22]))
(array(['to', 'select', 'a', 'piece'], dtype=object), array([ 0.52388737,  0.39941035,  0.45865621,  0.46943467]))
(array(['to', 'move', 'all', 'right'], dtype=object), array([  5.23887371e-01,   2.43874664e-13,   3.95621699e-01,
         3.55995401e-01]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'okay'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.51752287]))
(array(['so', 'so', 'it', "'s"], dtype=object), array([ 0.36887535,  0.36887535,  0.48151029,  0.482

(array(['__PADDING__', 'the', 'yellow', 'one'], dtype=object), array([ 0.        ,  0.50487925,  0.8713726 ,  0.37393538]))
(array(['__PADDING__', '__PADDING__', 'yeah', 'exactly'], dtype=object), array([ 0.        ,  0.        ,  0.4564016 ,  0.30998474]))
(array(['__PADDING__', 'it', "'s", 'the'], dtype=object), array([ 0.        ,  0.46676806,  0.44782556,  0.50487925]))
(array(['__PADDING__', '__PADDING__', 'yellow', 'thing'], dtype=object), array([ 0.       ,  0.       ,  0.8713726,  0.6281531]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'yeah'], dtype=object), array([ 0.       ,  0.       ,  0.       ,  0.4564016]))
(array(['__PADDING__', '__PADDING__', 'all', 'right'], dtype=object), array([ 0.        ,  0.        ,  0.49285751,  0.42723517]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'okay'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.49051975]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'okay'], dtype=object), array([ 0.   

(array(['the', 'red', 'piece', 'at'], dtype=object), array([ 0.45500616,  0.96455551,  0.48309168,  0.29075322]))
(array(['__PADDING__', 'the', 'top', 'right'], dtype=object), array([ 0.        ,  0.45500616,  0.89139286,  0.71232058]))
(array(['__PADDING__', '__PADDING__', 'top', 'right'], dtype=object), array([ 0.        ,  0.        ,  0.89139286,  0.71232058]))
(array(['__PADDING__', '__PADDING__', 'top', 'right'], dtype=object), array([ 0.        ,  0.        ,  0.89139286,  0.71232058]))
(array(['__PADDING__', 'so', 'it', 'looks'], dtype=object), array([ 0.        ,  0.4698081 ,  0.49801141,  0.44950114]))
(array(['__PADDING__', 'like', 'a', 'kind'], dtype=object), array([ 0.        ,  0.48415977,  0.47555488,  0.49392148]))
(array(['__PADDING__', 'of', 'like', 'a'], dtype=object), array([ 0.        ,  0.58562647,  0.48415977,  0.47555488]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'you'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.45009602]))
(ar

(array(["'s", 'a', 'green', 'V'], dtype=object), array([ 0.47899825,  0.4390844 ,  0.74315815,  0.95419301]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'yeah'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.41117961]))
(array(['so', 'the', 'place', 'where'], dtype=object), array([ 0.63588433,  0.55208019,  0.00179285,  0.38297503]))
(array(['I', 'selected', 'the', 'V'], dtype=object), array([ 0.74151189,  0.98968396,  0.55208019,  0.06963865]))
(array(['right', 'on', 'the', 'opposite'], dtype=object), array([  4.91796480e-01,   6.84771542e-01,   5.52080191e-01,
         6.50808105e-17]))
(array(['end', 'the', 'left', 'side'], dtype=object), array([ 0.99999951,  0.55208019,  0.92063744,  0.86775964]))
(array(['of', 'it', 'a', 'weird'], dtype=object), array([ 0.61767955,  0.5715637 ,  0.59060528,  0.90453653]))
(array(['looking', 'blue', 'color', 'thingy'], dtype=object), array([  4.41160145e-20,   8.43337824e-01,   5.38798835e-01,
         2.41419815e-01]))


(array(['__PADDING__', '__PADDING__', '__PADDING__', 'yeah'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.47353393]))
(array(['__PADDING__', 'yeah', 'yeah', 'nice'], dtype=object), array([ 0.        ,  0.47353393,  0.47353393,  0.38538197]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'awesome'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.98871269]))
(array(['okay', 'it', "'s", 'the'], dtype=object), array([ 0.4982041 ,  0.48694979,  0.48873926,  0.49350809]))
(array(['__PADDING__', 'big', 'weird', 'one'], dtype=object), array([ 0.        ,  0.59426673,  0.63816704,  0.54247137]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'mm-hmm'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.65563051]))
(array(['__PADDING__', 'in', 'the', 'bottom'], dtype=object), array([ 0.        ,  0.52207626,  0.49350809,  0.8619188 ]))
(array(['__PADDING__', '__PADDING__', 'the', 'big'], dtype=object), array([ 0.        ,  0.        

(array(["'s", 'small', 'and', 'blue'], dtype=object), array([ 0.4844315 ,  0.69559033,  0.33330232,  0.80424651]))
(array(['__PADDING__', 'ah', 'okay', 'yeah'], dtype=object), array([ 0.        ,  0.63682497,  0.49458457,  0.47102106]))
(array(['__PADDING__', 'the', 'big', 'one'], dtype=object), array([ 0.        ,  0.47688206,  0.77880482,  0.57213768]))
(array(['__PADDING__', 'again', 'the', 'pink'], dtype=object), array([ 0.        ,  0.51503738,  0.47688206,  0.5903158 ]))
(array(['__PADDING__', 'rectangles', 'tilt', 'yeah'], dtype=object), array([  0.00000000e+00,   4.70553934e-01,   2.99200934e-23,
         4.53465733e-01]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'yes'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.42388306]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'yeah'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.45346573]))
(array(['a', 'small', 'blue', 'rectangle'], dtype=object), array([ 0.53155637,  0.7581

(array(['__PADDING__', 'your', 'favorite', 'right'], dtype=object), array([ 0.        ,  0.29428662,  0.46815244,  0.47730433]))
(array(['__PADDING__', '__PADDING__', 'ah', 'yeah'], dtype=object), array([ 0.        ,  0.        ,  0.47095581,  0.47136428]))
(array(['__PADDING__', 'it', "'s", 'almost'], dtype=object), array([ 0.        ,  0.50523464,  0.50049495,  0.66060664]))
(array(['__PADDING__', '__PADDING__', 'Easter', 'so'], dtype=object), array([ 0.        ,  0.        ,  0.51826904,  0.52942014]))
(array(['ah', 'ooh', 'favorite', 'from'], dtype=object), array([ 0.48270102,  0.78630925,  0.51826904,  0.4995308 ]))
(array(['from', 'old', 'times', 'to'], dtype=object), array([ 0.4995308 ,  0.51826904,  0.51826904,  0.44463206]))
(array(['__PADDING__', 'the', 'right', 'you'], dtype=object), array([ 0.        ,  0.52627804,  0.68503676,  0.5038169 ]))
(array(['__PADDING__', 'have', 'this', 'yellow'], dtype=object), array([ 0.        ,  0.45482336,  0.50890734,  0.73700059]))
(array(

(array(['__PADDING__', '__PADDING__', '__PADDING__', 'yes'], dtype=object), array([ 0.       ,  0.       ,  0.       ,  0.2406775]))
(array(['now', 'from', 'the', 'bottom'], dtype=object), array([ 0.52790364,  0.39932738,  0.49971235,  0.74454528]))
(array(['from', 'the', 'middle', 'you'], dtype=object), array([ 0.39932738,  0.49971235,  0.53526659,  0.48422702]))
(array(['go', 'to', 'the', 'bottom'], dtype=object), array([ 0.6382729 ,  0.44773988,  0.49971235,  0.74454528]))
(array(['__PADDING__', 'and', 'you', 'have'], dtype=object), array([ 0.        ,  0.45564394,  0.48422702,  0.46853282]))
(array(['__PADDING__', 'this', 'pink', 'K'], dtype=object), array([ 0.        ,  0.63362885,  0.85760469,  0.99958515]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'yeah'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.55619891]))
(array(['__PADDING__', '__PADDING__', 'got', 'it'], dtype=object), array([ 0.        ,  0.        ,  0.59592569,  0.50938015]))
(array(['_

(array(['__PADDING__', 'to', 'describe', 'yeah'], dtype=object), array([ 0.        ,  0.47035455,  0.19420733,  0.49542226]))
(array(['__PADDING__', 'the', 'light', 'blue'], dtype=object), array([ 0.        ,  0.46978932,  0.62481682,  0.71742477]))
(array(['oh', 'light', 'blue', 'okay'], dtype=object), array([ 0.3869645 ,  0.62481682,  0.71742477,  0.51170379]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'nice'], dtype=object), array([ 0.       ,  0.       ,  0.       ,  0.3185521]))
(array(['oh', 'okay', 'so', 'this'], dtype=object), array([ 0.39400567,  0.51470846,  0.40674426,  0.43561803]))
(array(['one', 'is', 'green', 'it'], dtype=object), array([ 0.43574572,  0.4339006 ,  0.8632727 ,  0.47826534]))
(array(["'s", 'very', 'big', 'and'], dtype=object), array([ 0.45373621,  0.25353216,  0.6345361 ,  0.45298465]))
(array(['it', "'s", 'a', 'square'], dtype=object), array([ 0.47826534,  0.45373621,  0.42994868,  0.22726419]))
(array(['__PADDING__', 'and', 'triangle', 'okay']

         5.34345212e-42]))
(array(['__PADDING__', '__PADDING__', '`', 'kay'], dtype=object), array([ 0.        ,  0.        ,  0.47157776,  0.47189811]))
(array(['that', "'s", 'Batman', 'two'], dtype=object), array([  4.56910444e-01,   4.98849449e-01,   1.73539373e-24,
         2.96998100e-01]))
(array(['__PADDING__', 'the', 'other', 'one'], dtype=object), array([  0.00000000e+00,   4.85977434e-01,   9.05336840e-16,
         4.19937082e-01]))
(array(['__PADDING__', 'is', 'Batman', 'one'], dtype=object), array([  0.00000000e+00,   3.97013637e-01,   1.73539373e-24,
         4.19937082e-01]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'yeah'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.41709901]))
(array(['__PADDING__', '__PADDING__', 'face', 'red'], dtype=object), array([ 0.        ,  0.        ,  0.99288637,  0.86702873]))
(array(['__PADDING__', 'the', 'same', 'again'], dtype=object), array([ 0.        ,  0.47940344,  0.54864699,  0.28255326]))
(array(['__

(array(['who', 'is', 'first', 'me'], dtype=object), array([  6.23419547e-45,   6.38439264e-01,   5.08276833e-01,
         5.27482136e-01]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'who'], dtype=object), array([  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         6.23419547e-45]))
(array(['__PADDING__', '__PADDING__', 'it', "'s"], dtype=object), array([ 0.        ,  0.        ,  0.54989712,  0.55648308]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'yeah'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.59232416]))
(array(['__PADDING__', '__PADDING__', 'oh', 'okay'], dtype=object), array([ 0.        ,  0.        ,  0.52721954,  0.54481331]))
(array(['if', 'you', 'see', 'a'], dtype=object), array([ 0.16079841,  0.66890671,  0.70478672,  0.53728248]))
(array(['red', 'square', 'you', "'re"], dtype=object), array([ 0.17774944,  0.22167463,  0.66890671,  0.37056639]))
(array(['supposed', 'to', 'describe', 'it'], dtype=object), array([ 1.      

(array(['__PADDING__', 'the', 'man', "'s"], dtype=object), array([ 0.        ,  0.51835432,  0.98168685,  0.54050782]))
(array(['__PADDING__', 'face', 'in', 'yellow'], dtype=object), array([  0.00000000e+00,   9.83313955e-01,   4.46416146e-01,
         3.31472251e-39]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'okay'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.49566627]))
(array(['now', 'it', "'s", 'a'], dtype=object), array([ 0.54006925,  0.5337681 ,  0.53359833,  0.55258316]))
(array(['very', 'small', 'light', 'blue'], dtype=object), array([ 0.79386575,  0.83173293,  0.85457036,  0.71285459]))
(array(['one', 'directly', 'under', 'this'], dtype=object), array([ 0.56107039,  0.60012886,  0.62429498,  0.57367547]))
(array(['house', 'the', 'second', 'one'], dtype=object), array([ 0.48410907,  0.52847624,  0.35054193,  0.56107039]))
(array(['like', 'like', 'a', 'yeah'], dtype=object), array([ 0.58256998,  0.58256998,  0.55258316,  0.58466743]))
(array(['_

         5.42371540e-01]))
(array(['__PADDING__', "'s", 'a', 'red'], dtype=object), array([ 0.        ,  0.55176689,  0.4863921 ,  0.13752767]))
(array(['__PADDING__', 'red', 'sorry', 'pink'], dtype=object), array([ 0.        ,  0.13752767,  0.60553614,  0.91941794]))
(array(['it', 'has', 'like', 'two'], dtype=object), array([ 0.54237154,  0.62912088,  0.5311922 ,  0.48048157]))
(array(['triangles', 'that', 'look', 'a'], dtype=object), array([ 0.63652017,  0.52587034,  0.61678139,  0.4863921 ]))
(array(['bit', 'like', 'the', 'ears'], dtype=object), array([  7.39439842e-01,   5.31192195e-01,   5.22043796e-01,
         4.75261533e-11]))
(array(['and', 'then', 'one', 'triangle'], dtype=object), array([ 0.47845561,  0.62081447,  0.584502  ,  0.26122667]))
(array(['__PADDING__', 'with', 'a', 'base'], dtype=object), array([  0.00000000e+00,   4.11706607e-01,   4.86392102e-01,
         3.26578865e-10]))
(array(['__PADDING__', 'on', 'the', 'bottom'], dtype=object), array([ 0.        ,  0.42027

(array(['speech', 'bubble', 'in', 'a'], dtype=object), array([ 1.        ,  1.        ,  0.58789778,  0.51829233]))
(array(['comic', 'book', 'or', 'it'], dtype=object), array([ 1.        ,  0.51830835,  0.34595849,  0.50562404]))
(array(['__PADDING__', 'looks', 'also', 'a'], dtype=object), array([ 0.        ,  0.57867226,  0.75841099,  0.51829233]))
(array(['__PADDING__', 'bit', 'like', 'Texas'], dtype=object), array([ 0.        ,  0.57912446,  0.53512259,  0.51830835]))
(array(['__PADDING__', 'uh-huh', 'yeah', 'yeah'], dtype=object), array([ 0.        ,  0.4884154 ,  0.53156031,  0.53156031]))
(array(['__PADDING__', 'I', 'think', 'I'], dtype=object), array([ 0.        ,  0.62113429,  0.72607585,  0.62113429]))
(array(['__PADDING__', 'know', 'yeah', 'great'], dtype=object), array([ 0.        ,  0.50873585,  0.53156031,  0.44379579]))
(array(['I', 'I', 'think', 'I'], dtype=object), array([ 0.62113429,  0.62113429,  0.72607585,  0.62113429]))
(array(["'ll", 'try', 'it', 'with'], dtype=ob

(array(['oh', 'it', "'s", 'like'], dtype=object), array([ 0.43291994,  0.52497434,  0.51230992,  0.48073234]))
(array(['triangles', 'cut', 'out', 'from'], dtype=object), array([  4.92954185e-02,   8.00125230e-10,   7.74867734e-01,
         2.44634690e-01]))
(array(['two', 'sides', 'like', 'two'], dtype=object), array([  1.44860627e-01,   5.68260997e-19,   4.80732341e-01,
         1.44860627e-01]))
(array(['__PADDING__', 'little', 'white', 'triangles'], dtype=object), array([ 0.        ,  0.54258383,  1.        ,  0.04929542]))
(array(['__PADDING__', 'oh', 'the', 'ah'], dtype=object), array([ 0.        ,  0.43291994,  0.49733871,  0.4122374 ]))
(array(['__PADDING__', 'on', 'the', 'outline'], dtype=object), array([ 0.        ,  0.54784477,  0.49733871,  0.4430869 ]))
(array(['oh', 'I', 'should', 'wait'], dtype=object), array([  4.32919941e-01,   4.46008644e-01,   9.40556791e-19,
         3.98139974e-01]))
(array(['__PADDING__', 'oh', 'there', "'s"], dtype=object), array([ 0.        ,  0.

(array(['__PADDING__', '__PADDING__', 'like', 'a'], dtype=object), array([ 0.        ,  0.        ,  0.53502766,  0.43000063]))
(array(['__PADDING__', 'one', 'two', 'three'], dtype=object), array([ 0.        ,  0.4395992 ,  0.58194886,  0.27416058]))
(array(['__PADDING__', 'four', 'five', 'six'], dtype=object), array([  0.00000000e+00,   2.55076758e-01,   8.89753343e-01,
         4.01498358e-13]))
(array(['it', 'has', 'six', 'sides'], dtype=object), array([  4.65730209e-01,   4.60253558e-01,   4.01498358e-13,
         2.23223360e-01]))
(array(['and', 'there', "'s", 'some'], dtype=object), array([ 0.49146098,  0.50191928,  0.44976138,  0.66095142]))
(array(['__PADDING__', 'kind', 'of', 'bite'], dtype=object), array([ 0.        ,  0.49061968,  0.51332615,  0.55174714]))
(array(['__PADDING__', 'marks', 'in', 'it'], dtype=object), array([ 0.        ,  0.55174714,  0.44200868,  0.46573021]))
(array(['__PADDING__', '__PADDING__', 'like', 'like'], dtype=object), array([ 0.        ,  0.       

(array(['looks', 'like', 'a', 'computer'], dtype=object), array([ 0.47871457,  0.40418153,  0.47462331,  0.98271343]))
(array(['and', 'it', "'s", 'greenish'], dtype=object), array([  5.10019917e-01,   5.21793836e-01,   5.00344436e-01,
         5.16585872e-07]))
(array(['__PADDING__', 'greenish', 'yes', 'a'], dtype=object), array([  0.00000000e+00,   5.16585872e-07,   2.90188278e-01,
         4.74623306e-01]))
(array(['__PADDING__', '__PADDING__', 'big', 'one'], dtype=object), array([ 0.        ,  0.        ,  0.26296707,  0.47812288]))
(array(['yeah', 'the', 'big', 'one'], dtype=object), array([ 0.47113786,  0.51747688,  0.26296707,  0.47812288]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'correct'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.17096522]))
(array(['okay', 'so', 'it', "'s"], dtype=object), array([ 0.5085447 ,  0.60168122,  0.49985489,  0.5020483 ]))
(array(['again', 'the', 'purple', 'with'], dtype=object), array([ 0.46436169,  0.51867785,  

(array(['yeah', 'it', "'s", 'the'], dtype=object), array([ 0.51438258,  0.49229513,  0.46209475,  0.52472751]))
(array(['same', 'blue', 'yellow', 'spaceship'], dtype=object), array([ 0.69518942,  0.02012393,  0.90229993,  0.89179557]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'yellow'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.90229993]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'yeah'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.51438258]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'oh'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.45979892]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'cool'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.51435167]))
(array(['__PADDING__', 'the', 'green', 'V'], dtype=object), array([ 0.        ,  0.47291757,  0.79788792,  0.90656318]))
(array(['__PADDING__', 'it', "'s", 'the'], dtype=object), array([ 0.        ,  0.47369939, 

(array(['or', 'bird', 'or', 'whatever'], dtype=object), array([ 0.38840449,  0.72865404,  0.38840449,  0.66999066]))
(array(['the', 'big', 'yellow', 'thing'], dtype=object), array([ 0.50452623,  0.56912103,  0.61561723,  0.74134284]))
(array(['with', 'lots', 'of', 'triangles'], dtype=object), array([  4.37684011e-01,   1.22790018e-08,   5.96528594e-01,
         7.56281493e-01]))
(array(['the', 'small', 'blue', 'TV'], dtype=object), array([ 0.50277968,  0.62561804,  0.74058884,  0.97643972]))
(array(['the', 'light', 'blue', 'emerald'], dtype=object), array([  4.88552249e-01,   3.76127934e-01,   7.42918031e-01,
         2.84771088e-10]))
(array(['__PADDING__', 'the', 'light', 'blue'], dtype=object), array([ 0.        ,  0.49850087,  0.75410024,  0.63284733]))
(array(['__PADDING__', 'mountain', 'very', 'small'], dtype=object), array([ 0.        ,  0.97788932,  0.2947244 ,  0.79484728]))
(array(['__PADDING__', 'the', 'small', 'kind'], dtype=object), array([ 0.        ,  0.48022423,  0.5177

(array(['okay', 'it', "'s", 'pink'], dtype=object), array([ 0.46824597,  0.51810128,  0.52866662,  0.89296717]))
(array(['and', 'it', "'s", 'a'], dtype=object), array([ 0.56199331,  0.51810128,  0.52866662,  0.61688262]))
(array(['little', 'bit', 'down', 'than'], dtype=object), array([  2.15342347e-01,   5.25152637e-01,   4.31057644e-01,
         7.27326217e-11]))
(array(['__PADDING__', 'the', 'bird', 'pink'], dtype=object), array([ 0.        ,  0.51830343,  0.16789492,  0.89296717]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'mm-hmm'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.44976004]))
(array(['do', 'you', 'see', 'a'], dtype=object), array([ 0.52174189,  0.54115676,  0.48757575,  0.61688262]))
(array(['__PADDING__', 'bird', 'pink', 'like'], dtype=object), array([ 0.        ,  0.16789492,  0.89296717,  0.5153262 ]))
(array(['__PADDING__', 'in', 'the', 'middle'], dtype=object), array([ 0.        ,  0.61361408,  0.51830343,  0.83370321]))
(array(['__PA

(array(['__PADDING__', '__PADDING__', 'light', 'green'], dtype=object), array([ 0.       ,  0.       ,  0.4963843,  0.9101263]))
(array(['the', 'crazy', 'grass', 'with'], dtype=object), array([  5.01865745e-01,   5.88106358e-18,   5.85001042e-01,
         5.40375119e-01]))
(array(['the', 'lighter', 'green', 'color'], dtype=object), array([ 0.50186575,  0.61212998,  0.57387434,  0.5894747 ]))
(array(['__PADDING__', 'the', 'coniferous', 'tree'], dtype=object), array([ 0.        ,  0.51305371,  0.56721412,  0.81865781]))
(array(['__PADDING__', '__PADDING__', 'in', 'blue'], dtype=object), array([ 0.        ,  0.        ,  0.55515466,  0.69684435]))
(array(['slanted', 'rectangle', 'with', 'two'], dtype=object), array([ 0.56765902,  0.71809349,  0.31655651,  0.56196587]))
(array(['__PADDING__', 'triangles', 'in', 'purple'], dtype=object), array([ 0.        ,  0.28575981,  0.54390796,  0.55192194]))
(array(['__PADDING__', '__PADDING__', 'the', 'diya'], dtype=object), array([ 0.        ,  0.  

(array(['I', 'think', 'it', "'s"], dtype=object), array([ 0.50510085,  0.34810138,  0.47873219,  0.50157333]))
(array(['__PADDING__', 'the', 'only', 'one'], dtype=object), array([ 0.        ,  0.47113876,  0.38356262,  0.53603122]))
(array(['__PADDING__', 'in', 'that', 'color'], dtype=object), array([ 0.        ,  0.48869541,  0.47375559,  0.48636616]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'yeah'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.47700633]))
(array(['__PADDING__', 'it', "'s", 'a'], dtype=object), array([ 0.        ,  0.50186542,  0.49432855,  0.4649161 ]))
(array(['__PADDING__', 'chicken', 'yellow', 'chicken'], dtype=object), array([ 0.        ,  0.98913663,  0.77436549,  0.98913663]))
(array(['__PADDING__', '__PADDING__', 'hen', 'or'], dtype=object), array([ 0.        ,  0.        ,  1.        ,  0.66274288]))
(array(['__PADDING__', '__PADDING__', '__PADDING__', 'bwok'], dtype=object), array([ 0.        ,  0.        ,  0.        ,  0.477

In [58]:
for seq in score_seqs:
    print("scoreseq")
    for s in seq:
        print("s")
        for something in s:
            print(something)


for seq in word_seqs:
    print("seq")
    for t in seq:
        print("t")
        for something in t:
            print(something)

scoreseq
s


TypeError: 'numpy.float64' object is not iterable

In [20]:
import itertools

from sklearn.preprocessing import LabelEncoder

all_words = tuple(itertools.chain(("__PADDING__", ), cv_results["WORD"].values))
print("Converting {} vocabulary entries to integer labels.".format(len(all_words)), file=sys.stderr)
# integer encode <https://machinelearningmastery.com/how-to-one-hot-encode-sequence-data-in-python/>
label_encoder = LabelEncoder()
label_encoder.fit(all_words)
for word_seq in word_seqs:
    integer_label_seq = label_encoder.transform(word_seq)
    print(integer_label_seq)
#integer_label_seqs = tuple(label_encoder.transform(word_seq) for word_seq in word_seqs)
#print(integer_label_seqs)

Converting 60343 vocabulary entries to integer labels.
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:128: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[101 857 844  37]
[1059   85 1065  924]
[ 105 1023]
[1330  526  876  937]
[1246 1064   85  924]
[1246  805  105 1023]
[857]
[1118 1118  672    5]
[ 105 1023]
[672   5  85 928]
[ 300  690  851 1246]
[1217  707  722   85]
[870 722  85 999]
[1216    5  703  422]
[857]
[1021]
[789]
[670 672 186]
[1217  575  861]
[1385 1385  465]
[ 105 1023  670]
[ 672 1232  861]
[1217  876  937 1065]
[1217 1023  924]
[913]
[ 105 1023]
[568 680]
[1118   37  844]
[ 600 1246  415]
[1217  833 1281]
[1023]
[ 105 1023 1118  844]
[  37  600 1217  924]
[118 672   5]
[1381  651  300]
[1290]
[118 672   5 722]
[ 85 522 197]
[ 143 1217  218]
[ 105 1023  857  913]
[1380]
[1330  857  331 1246]
[ 833 1281  105 1023]
[1118 1118  672    5]
[ 651 1217  707  741]
[337 722  85 429]
[ 870 1122  871]
[789]
[722  85 207 429]
[1380]
[871]
[ 870 1003  871]
[ 37 415 817]
[ 694  996 1380]
[857]
[ 105 1023  857]
[1388 1045  672]
[  5  85 429]
[1380  707  741  337]
[789]
[ 857  844   37 1059]
[  37 1334  734  143]
[1217 1023  861 1125

[   5 1343  601 1332]
[1380 1380 1380]
[1217 1217  575 1030]
[ 651 1217  451 1336]
[1217  728  575 1030]
[1380]
[37  3]
[857  37]
[857 844]
[1388 1059 1122  844]
[ 672 1047 1064]
[ 924 1246  805]
[ 105 1023  857  844]
[  37 1059 1122  857]
[ 651 1217  218 1023]
[ 337 1221    5 1221]
[  5 722 672 735]
[722 117 455]
[1216    5  927]
[1023   37   37]
[1059 1287]
[ 857 1217  861 1246]
[1217 1217 1217  797]
[1217 1110  861]
[1380 1217 1110  861]
[ 143  143 1217  218]
[ 218  218 1023]
[1380]
[1118 1216    5]
[1217  861]
[1384]
[ 287 1216  861]
[ 150  568 1372]
[857]
[1380 1023]
[857]
[1118  844  672    5]
[ 115   37 1178 1246]
[ 287  833 1281]
[1380]
[1023]
[ 37 570]
[ 857 1118  672    5]
[ 85  85 927 924]
[ 857 1118 1388]
[1246 1217  707 1246]
[1217  707 1089 1124]
[ 651 1217  774 1388]
[1059   85   85 1003]
[ 924  118 1246]
[1217  218 1023]
[ 851 1216  924]
[1380]
[789]
[1329 1329 1343 1343]
[ 300  670 1217  924]
[1118  672    5  969]
[  37    1 1045]
[857  37  37]
[ 118 1118]
[  37 1059  

[836 672   5 841]
[672   5 841]
[  88 1217  999]
[672   5]
[1118  143 1217]
[1252 1023]
[1329]
[1118  672    5   88]
[1217 1129 1084 1225]
[ 857   88 1217 1130]
[1225  118  672    5]
[672   5 672   5]
[ 855 1329 1118  672]
[ 859 1217 1023]
[672   5]
[ 510 1336  600 1217]
[1136  118 1220 1336]
[ 600   85 1225  118]
[ 670 1216   85 1225]
[1216    5  690  851]
[735 722  85  72]
[1126  851  118 1221]
[   5   85 1269]
[ 651 1217  774]
[1380  465 1216]
[1216  861]
[118 672   5 927]
[857 334]
[1217 1217  928]
[1380]
[ 105 1023]
[857 844 672   5]
[1217 1225 1216   37]
[1334 1046  432]
[1118  672    5  722]
[ 85 904 672   5]
[ 651 1217  774  118]
[672   5 927]
[672   5 859]
[1217 1023  851]
[ 851 1217   72]
[1380]
[1023]
[150]
[ 857 1118  672    5]
[1217 1004  799  734]
[1225 1260 1217  218]
[ 722 1217  218  707]
[670 672 651 722]
[1374 1336 1045 1217]
[1225 1216    5  722]
[1246 1217 1023  851]
[1217  602 1227]
[1380]
[1217]
[1380]
[1023]
[465]
[857 844 672   5]
[ 857   88 1217   72]
[1217 121

[ 855 1232  670  855]
[1232  861  670  832]
[672   5 871 118]
[672 596 532 532]
[ 907  118 1220]
[162 105 537]
[1217 1040  580]
[857 715   5]
[244 672]
[735 722  85 254]
[254]
[568]
[788]
[1217  273]
[1232  861  670]
[112 832]
[672 670 732]
[1388  114  553 1217]
[832 862 571 857]
[672 670]
[1380]
[1232  861 1381  118]
[672 596  85 193]
[1261  118 1261]
[715   5 244]
[672 715   5]
[244 672  56]
[1217  892]
[1217  892]
[1217  892]
[1217  892]
[1217  892]
[1217  892]
[63]
[1232  670   85 1213]
[ 851  764 1011]
[1380]
[857]
[  84  683 1388]
[1388  561]
[1217  670  672  344]
[  85  344 1155 1300]
[622 282 236 207]
[ 193  870 1110]
[1155 1300  622  284]
[ 983 1110]
[ 193  870 1110]
[ 983 1110]
[1110]
[1380  983 1110]
[855 836]
[540]
[1216 1334 1217]
[ 193  861 1083]
[857]
[640]
[815 156]
[1216 1334 1217]
[1110  861]
[857]
[ 836 1217  195  861]
[855 857]
[1125]
[815]
[815 156]
[  37  397  817 1059]
[1217 1110  861]
[1388  561  102 1388]
[ 561 1388  331]
[836  37 242 817]
[ 672 1047 1330  526]

[571]
[ 84 683]
[1118 1217  800]
[1216  131  859]
[1217  259  707]
[1384]
[1217   80]
[1384]
[1217  255]
[1217  255]
[ 255 1184  259  707]
[1380   37    3]
[1056  526  672]
[1380  570  672]
[1217   12   88 1217]
[ 575  534 1217 1252]
[101]
[570 672]
[1384]
[1217  479 1347  670]
[ 143 1217  218  259]
[1384]
[570 672]
[1380]
[1217   49  927]
[  49  651 1217]
[1126  851  774]
[1217  861 1216    5]
[ 833 1246 1217 1030]
[1380  465]
[857]
[1217  535 1347  670]
[ 833 1246 1217 1030]
[1252]
[570 672]
[1380]
[1217 1030  675]
[1217  255 1184 1347]
[670  99 143]
[1217  259  707]
[570 672]
[1217   12 1216]
[1334  833 1246]
[1217  255 1184]
[1384]
[1217   80 1347  670]
[ 186 1217  792]
[ 651 1217  259]
[1380  570  672]
[1217  479 1217  927]
[ 479  859 1217  707]
[1089  118 1343 1300]
[1380 1023  571]
[1118 1217   49 1216]
[ 5 88  8 72]
[ 118 1246 1217 1023]
[ 851 1217   80]
[1217  927  861]
[ 870 1217]
[1217  927  861]
[1380]
[570 672]
[1217  534  218  259]
[1384]
[571]
[1118 1217  207    8]
[  72

[ 672    5 1232  670]
[1217  927 1073 1217]
[1339 1073  859]
[1217  707 1089]
[ 651 1217  774]
[1365  105 1217 1270]
[1365 1217 1380 1380]
[1380 1217 1339 1073]
[1329  672  416  105]
[ 105 1217 1270]
[1380  537  105]
[1217 1091 1380]
[1380 1380 1380]
[ 37 244 672]
[1217 1339 1073]
[1380  857 1339 1073]
[1380]
[844 672   5  85]
[193 575 396]
[1232  861]
[834]
[789]
[ 672    5 1217  969]
[ 354  291 1246 1217]
[ 193   72 1300]
[ 855 1388 1228  672]
[  5  85 354 841]
[ 85 282 236]
[ 672    5 1217]
[1040  861 1023]
[  37 1380  672    5]
[ 189   37 1217]
[ 282  833 1246]
[1217  193   72]
[1300]
[1232  861 1385 1118]
[672   5  85]
[969 354 857]
[1380]
[1380]
[1380  241 1217  282]
[ 85 207 197 859]
[1217 1023 1089]
[1216    5 1023]
[1385  834]
[ 672    5 1217  135]
[1216    5  482  422]
[ 859 1217  707]
[1089 1216  861]
[ 291 1246 1217   46]
[ 855 1023 1380  186]
[1380 1246 1217  707]
[1380]
[789]
[193  46]
[ 193 1385]
[969  46]
[1217  193  636  859]
[1217 1023 1089]
[207]
[1380 1217  207 1118

[101]
[570 672]
[ 844  672    5 1217]
[1026 1365   85  597]
[1246 1217 1023]
[ 851 1217  752]
[ 651 1217  597]
[570 672]
[ 844  672    5 1217]
[1003   72   99]
[789]
[420]
[118 844 672]
[   5 1217 1026]
[ 651 1217  597]
[1026  651 1217  597]
[844 672   5]
[1217 1285   80]
[789]
[570 672]
[118 844 672   5]
[1217  575  947   72]
[ 859 1217 1252]
[1385]
[844 672   5  88]
[1217 1130   85]
[  85  969 1027]
[ 101  969 1110]
[1027  857]
[1385]
[857 844 672   5]
[1217 1217  273  651]
[1217 1023  575  273]
[ 651 1217 1023]
[ 337 1252  337]
[570 672]
[855 844 672   5]
[1217  193  575   72]
[1365   85  943]
[101]
[570 672]
[857 844 672   5]
[1217  969 1110 1027]
[ 143 1217 1252]
[570 672]
[ 844  672    5 1217]
[1217  193  969  254]
[101]
[420]
[857 844 672]
[   5 1217 1008]
[ 927 1008 1225]
[570 672]
[ 844  672    5 1217]
[1217  207 1026]
[1365   85  597]
[101]
[570 672]
[857 844 672   5]
[1217 1285   80]
[ 844  672    5 1217]
[1217  207 1026  651]
[1217 1252  707]
[ 841 1217 1026]
[1365   85  59

[969 197 734]
[1246 1217  707]
[1217  193   72 1365]
[1217 1269 1300  207]
[1380]
[ 397  125 1388  118]
[ 37 958 857]
[842 670 593]
[37]
[ 855  857 1329 1125]
[ 672 1037 1216  672]
[1334 1217 1378]
[672   5  85 207]
[  72 1365   85  943]
[ 651 1217  774 1300]
[857]
[ 857 1118 1217  924]
[ 670 1217  861  143]
[1217  218 1257]
[ 143 1217  707]
[722  85  85]
[857]
[857]
[722  85 254]
[1385 1385]
[  85  799 1380]
[857 672   5 826]
[ 143 1217 1040  931]
[672   5  85 207]
[575 861 722]
[ 85 199 653]
[1217 1217 1217  794]
[ 143 1217  218]
[ 859 1217  707]
[ 37 600 842 143]
[1217  218  707]
[ 37 600 842]
[1380]
[ 415 1388 1059 1217]
[ 415 1388 1059 1217]
[ 193 1381  861]
[218 707 836]
[ 836 1388 1059]
[1217  193 1217]
[ 196 1381  861]
[722  85  63]
[1385]
[1388  561  422 1232]
[ 861 1232  861  416]
[ 722   85 1268]
[1385]
[ 672    5  841 1232]
[ 861  672    5 1158]
[ 794  859 1217  218]
[857 672   5 722]
[ 85 396 857]
[722  85 396]
[1385   37  287]
[857 568]
[1389 1281]
[ 101  672    5 1217]
[

[ 584  722 1236 1242]
[789]
[1380]
[1216  861 1380]
[1380]
[1216    5   85]
[952 861]
[ 101 1040   99 1217]
[1381  799 1073]
[1260 1217  218]
[1380]
[857]
[1336  600  491]
[ 37 582]
[1380]
[ 101  857 1388]
[1010 1217  320]
[ 841 1216  861]
[1384]
[1380]
[ 841 1216  861 1217]
[ 861  186 1217  576]
[722  85]
[1217  207 1217  396]
[1380]
[ 396  575 1227 1380]
[1384]
[857]
[ 84 683]
[1217 1315 1252]
[1023 1217   55]
[1365   85  840]
[1384]
[1315 1110  840]
[526 184  85]
[ 55 236 857]
[841 176 745]
[1315  811]
[1380]
[ 857 1118 1217   76]
[ 72   8 207 193]
[1073 1246 1217  707]
[1246 1217  707]
[1380]
[ 415 1388 1228 1336]
[ 600 1246  168  487]
[ 651 1232  548]
[ 37 415 817 694]
[ 857 1217  193  871]
[1073  651 1217  774]
[1096 1246 1343  601]
[ 584  700 1240]
[1217  861 1365]
[1217 1100 1091]
[1380]
[ 833 1246 1217]
[875 197]
[1380]
[1380 1216  861]
[857]
[1384]
[ 855 1232  670  117]
[661 861 672   5]
[193 118 927 118]
[672 735 722  85]
[722  85 166]
[1246 1217 1023]
[789]
[1228   37  570 

[ 957  857  101 1246]
[1217  833 1281]
[ 844 1388  600]
[1246 1208  764]
[ 844  815 1281  857]
[1118 1232  670  651]
[1217  651 1217  259]
[1388 1059 1221  670]
[ 85 207 861 672]
[   5  722   85 1051]
[1388  561   85  728]
[ 859 1217   85  728]
[1246 1217 1252  118]
[ 728  859 1217  707]
[1221    5 1232]
[1003  728  636]
[1385]
[ 672    5 1216  861]
[1216  861]
[1380 1221 1388  561]
[101 857]
[  85  731 1335]
[ 857 1345 1388    4]
[ 422 1221    5 1232]
[ 728  575 1225 1347]
[735 722  85]
[620  85 799]
[1365 1236 1255]
[1385 1385]
[ 422 1023 1089  270]
[1216 1192 1216  861]
[1217  207 1380]
[1217  836  836  575]
[ 101 1217  575]
[ 861 1380 1380]
[ 857  844 1388  600]
[1246 1208  764]
[ 857 1232  670  682]
[ 651 1217  218  707]
[ 337 1388  600 1232]
[ 207  722  672 1062]
[722  85 197 870]
[1122  857  672]
[  5 718 207]
[1380  722   85]
[ 722   85 1248]
[1216  861]
[1380 1380  722]
[  85 1248 1380]
[1380   37  722 1232]
[857]
[ 857 1336    4  568]
[1336    4  568]
[857 844 672   5]
[ 672 

[ 857  561 1246 1217]
[ 218  707  337 1221]
[ 670 1232   18]
[ 651  575 1380]
[1380]
[ 718  575 1380]
[1380]
[1248  859 1217  741]
[1023 1089  227 1248]
[1385]
[ 857  651 1217]
[1252  707  337]
[1217   24  256]
[ 857 1380]
[1248  859 1217]
[1252  718  207]
[1385]
[ 859 1217  861 1217]
[ 707 1217 1145  118]
[1217 1269 1223  131]
[651 651 969]
[1380]
[570 672]
[1388 1192 1217  197]
[ 651 1217  774 1324]
[1385]
[1388 1192 1217  800]
[ 859 1217  859 1217]
[ 218  707 1388  694]
[1217  575  800]
[1380]
[570 672]
[1380]
[1388 1192 1217]
[ 479 1301 1023]
[337 718 575]
[1385]
[1388 1192 1217 1003]
[1150   85  728]
[ 859 1217 1252]
[ 859 1217  707]
[1380]
[1217 1003 1150 1380]
[1380]
[1388 1192 1217  197]
[ 859 1217 1252  651]
[1217  774 1324]
[1380]
[ 969 1344]
[ 118 1388 1192 1217]
[ 800  859 1217]
[ 218 1023  992]
[718 575]
[575 800]
[ 718  575 1380]
[ 718  575  800 1380]
[1380 1380 1380]
[1388 1192 1217]
[ 349 1225  422]
[1221    5 1217   63]
[1051  118 1023  833]
[1246  672 1221    5]
[  85

[85]
[1385]
[ 672    5 1217  871]
[1069  851 1343  735]
[ 722  800 1140  862]
[  88 1217  927  636]
[1217  969  677]
[ 440 1058 1032]
[969 677 439]
[1380 1058 1032]
[1252  851 1217 1051]
[1217  800 1217]
[ 774 1252  774]
[871]
[ 871 1380 1125]
[969 907 707]
[1252  337]
[1252  707  337]
[1217  800  871]
[969 851 988 969]
[907 707 590 337]
[707 590 337 143]
[1217  218  707]
[927 927 969 969]
[1300 1252 1023]
[ 537 1217  637]
[ 186 1385]
[ 186 1217  282  857]
[1385]
[1380]
[ 672    5 1217  861]
[ 189 1217  672    5]
[1217  207  847  192]
[1217   63  118 1217]
[1217  575  479]
[1140  861]
[1217  839  851]
[1216  871  988]
[ 871 1217 1350]
[1347  862 1217]
[ 189 1217  927   46]
[1118  672    5]
[ 85 893 207]
[836 871 988]
[ 855 1217  871]
[988 857]
[1235  672 1334  189]
[1217  871  988 1125]
[1217  282  893]
[207 283 847]
[ 207   63 1051]
[ 101  218 1023  590]
[ 337 1217  360  575]
[ 969  988 1252]
[707 590 337]
[790]
[ 189 1217  927]
[636 670  85]
[ 893  207 1114]
[1380]
[927 636 707]
[590

[672   5 735 106]
[ 722   85 1248  672]
[  5 722 836 763]
[ 722   85 1248]
[ 672    5  595 1246]
[1059  236  672    5]
[ 672    5 1315  399]
[ 537  105 1217]
[ 876 1075  672]
[  5 193 112]
[118 927]
[1380  672    5  927]
[672   5 722]
[1380]
[1343 1217 1217]
[1145 1269  861]
[836]
[836]
[ 37 765 672   5]
[836 672   5 735]
[735 722  85 167]
[763 870 836]
[ 37 765 672   5]
[ 672    5   85 1073]
[ 118 1220 1221  670]
[1380   37  765]
[ 855 1217  861]
[  37 1228  735]
[722  85 197]
[1380  672    5]
[1315  193  672]
[   5 1315  193]
[1083]
[763 672   5 722]
[722 672 735 722]
[  85  273  945 1023]
[273]
[763  37 415 817]
[ 694 1388  249 1276]
[  37    2 1276]
[1380]
[ 672 1334 1217]
[1023  861]
[857]
[1380]
[118 844 672   5]
[1217  728   17  479]
[ 855 1217  479  857]
[1380]
[ 857 1118 1232  670]
[  85  354   85 1003]
[ 354 1315  193]
[1217  193  463  322]
[1380]
[1232  670 1217  207]
[1216  735  722   85]
[ 197  870 1122]
[722  85  46]
[ 788 1217  207]
[ 855  857 1217]
[ 417 1380]
[1217  19

[1217 1023 1089  833]
[1246 1217  361]
[575 799]
[  85 1110  583]
[ 833 1246 1217]
[575 799 207]
[1217  479]
[1380 1217  479]
[1003  479  707]
[1380]
[1217 1110  207 1225]
[ 186 1217  575  799]
[774]
[1003  479]
[1217  207 1225 1216]
[735 690 851]
[ 722   18 1110]
[ 859 1217  707]
[1217 1230  207]
[ 537 1217 1252]
[1216    5  841]
[ 841 1217  479]
[ 84 683]
[1216    5   18 1287]
[1217  876  861]
[670  18 861]
[1380]
[ 479 1003]
[1217 1040   99]
[1217  210 1225]
[799 575]
[193]
[207 575 479 707]
[207 575 479 707]
[774]
[ 18 218 969]
[ 135  859 1217  707]
[207 135]
[ 320 1252  707]
[1140 1225  859]
[1217 1023]
[1381  576]
[ 479 1003]
[1217  207   18  774]
[ 361  218 1023]
[1140 1225  207]
[218 707]
[1380]
[715   5 244]
[ 672   85 1117]
[1117  857]
[  18 1287  207]
[1110  207]
[361]
[575 799]
[479 774 707]
[320 969 774 218]
[1217  855  672    5]
[  85 1003 1225]
[ 651 1217  774]
[1246 1217  707]
[672   5  85]
[  76 1225]
[421]
[1217 1217]
[ 833 1246 1217   18]
[1287 1246 1217  207]
[ 861 

[1381 1073  833 1246]
[1217  207 1051]
[1246 1217 1023]
[1217 1110  861 1380]
[1380]
[118 844 672]
[   5 1217  166]
[ 859 1217  707]
[844 672   5]
[1217  166]
[ 844  672    5 1232]
[1269  118 1145  833]
[1246 1217  575  199]
[422 118 707 722]
[ 707 1380   37]
[570 672]
[ 192 1217 1380]
[ 844  672    5 1217]
[ 193 1381  799 1365]
[ 532  907 1155 1300]
[1023]
[ 105  851 1219  131]
[1023]
[722  85 193 354]
[ 193  354 1380]
[ 844  672    5 1217]
[1236  575  800]
[844 672   5]
[1217  193   72]
[ 651 1217  774]
[1217  193   72]
[844 672   5]
[1217  575  999]
[1246 1217  707]
[1023  422  422]
[ 707  833 1246]
[1217  565  197]
[1380]
[118 844 672   5]
[1217 1252  707]
[1217 1217  193]
[1217  193  575  668]
[ 575 1073 1380]
[1380]
[ 672    5 1217 1030]
[ 871 1030  833]
[1246 1217  166]
[118 844 672   5]
[1217   65 1210  859]
[1217  218 1032]
[789]
[1217 1110 1381 1300]
[1246 1217 1023]
[844 672   5]
[1217  166]
[1217  166]
[ 844  672    5 1217]
[1269 1365   85 1145]
[1246 1217 1023 1294]
[1217 

[1217  961 1390]
[1380 1125]
[857]
[1118 1221 1336  561]
[ 844 1336  570  672]
[857 844 672   5]
[1217  961   80   40]
[ 788 1003]
[1380  118  672]
[670  85]
[422 707 337]
[218 707]
[1380]
[789]
[1380]
[857]
[672 670 722  85]
[ 320 1051  672  670]
[ 833 1246 1217 1339]
[ 602 1217  927  861]
[ 855 1380 1179]
[1216  735  722]
[  85  320 1051]
[ 37 100]
[ 857 1232  861    5]
[ 690  851 1339]
[672   5 575]
[1385]
[118 672   5 651]
[ 192 1217  354 1074]
[1225  118 1217]
[ 947  969 1225]
[ 37 415 817]
[694 638 446]
[1246  385  672]
[1380  672  670 1122]
[722  85 296]
[1380   85  117]
[ 442  296 1179]
[ 672    5   99 1217]
[ 320 1051  118]
[672 670  85]
[1110  320 1052]
[ 855 1380 1179 1380]
[612   5 863]
[ 861  851 1233]
[570 672]
[855 672   5]
[1217 1040  575]
[ 296 1074 1225]
[1380  672    5  651]
[1217 1023  337]
[1380 1380]
[574]
[ 844 1336    4]
[419 568]
[1050  670  563 1300]
[672 670  85  85]
[ 575 1073  722]
[117  46 651]
[1217 1023  218]
[ 857 1380]
[  46 1074]
[  46 1074  575 1225]

[672   5  85 207]
[734 718 207 836]
[ 764 1380  690  851]
[718 207 236 672]
[  5 734 722  85]
[ 636  651   85 1073]
[851 636 672]
[  5 722  85]
[789]
[1217  444  871  861]
[1217 1040 1073]
[1380]
[1217  871  861]
[1217 1040 1073]
[857]
[1380  672    5  207]
[1315  718  207  118]
[672   5 722  85]
[1365 1270  859   85]
[1252  735  722  634]
[ 672  670 1381]
[402 112 672]
[  5  85 556]
[857]
[857 672   5]
[  85  989 1003]
[ 300 1365   85]
[ 672  670 1381]
[635 851 377]
[ 672    5   85 1110]
[1324  672  670]
[ 651 1217 1073]
[851 207]
[1380  651 1217]
[1073  851  207]
[672 735 722]
[672 670 207 651]
[1217 1073  851   72]
[857]
[672   5  85 718]
[207 924 734]
[722  85 636]
[624]
[672 670  85 927]
[ 969 1324  300  672]
[   5   85 1264]
[1365   85 1145]
[ 859 1217 1252]
[672   5  85 575]
[  72 1073 1365]
[1269  859 1252]
[1365  861 1269]
[ 859 1217 1252]
[1380 1365  861]
[1269  859 1252]
[ 672  670   85 1110]
[ 207  855 1365]
[ 836  651 1217]
[1073  851  392]
[ 672    5 1217  575]
[ 861  651

[857]
[ 857 1217  300  670]
[207 844 718 836]
[ 768  207  118 1220]
[672 596 722  85]
[ 999  118   85 1269]
[1217  999  670]
[ 859 1217 1269]
[789]
[857]
[857]
[ 101 1118 1217  300]
[670 690 851 192]
[ 927  118 1003   37]
[1374 1045  941 1118]
[672   5 672 735]
[722  85 999 236]
[ 596 1287  728 1270]
[184 363 852]
[857]
[416 672 732]
[722  85 752]
[85]
[537 622 964]
[ 836   37 1374 1045]
[672 735 722  85]
[  85 1269  836  999]
[1216    5  176  363]
[ 852 1217  217]
[1301 1301  338]
[ 851 1217  999]
[857]
[ 857   37 1228]
[ 37 694]
[ 857 1385]
[ 857  672    5 1217]
[1040  861  137 1217]
[1217  510  861 1217]
[1008 1365 1217]
[511 907 118]
[1217 1381  861]
[101]
[855 857 857]
[1380  672    5  672]
[   5 1381  118  672]
[  5  85 799]
[1365 1236  907]
[ 857 1353  670  672]
[ 419 1217 1040   99]
[ 37 415 817 694]
[ 857 1118 1232  861]
[670 207 370 207]
[118 672 735  85]
[199 722  85  85]
[197 672 596]
[ 722 1287 1269]
[ 118  422 1380]
[857]
[ 857 1232  861  670]
[207 118 672 735]
[722  85 7

[ 857  670 1216  672]
[ 855 1380 1388]
[570 672]
[857]
[1388  600 1246  919]
[1217 1023  861]
[ 857 1118 1232  861]
[ 670 1381  118  672]
[  5 722 117  46]
[1074  672    5  861]
[ 851 1217  195 1075]
[570 672]
[857]
[  99 1217   13 1225]
[857]
[ 84 683 672   5]
[1217  207  964  207]
[752   5 964]
[857]
[672   5 861]
[ 851 1217  728]
[ 871  421 1270]
[857]
[672   5]
[526 788 526 764]
[ 672    5  859 1217]
[707  37 415 817]
[ 694  646 1388  600]
[1217 1040 1051]
[741 707  37 415]
[817 694 118]
[624]
[857]
[672   5  85]
[193 207  72]
[857]
[1217  193  575  354]
[ 84 683]
[1217  575  207]
[197 964]
[1217  861 1216   37]
[1037  735   85  199]
[ 722   85  984 1365]
[1217  433  859 1252]
[1232  861    5  143]
[1217 1315  218]
[857]
[1217 1381 1073 1216]
[  5 672   5]
[682 722  85]
[392 690 851]
[570 672]
[1380]
[1217  197  207  964]
[857]
[1217  861 1216 1388]
[1037  735  722   85]
[ 984 1216    5]
[ 859 1217 1252]
[672 735 722  85]
[  85   85 1110  927]
[ 799 1022  861]
[ 193 1269  651]
[570

[672   5 718 207]
[ 118 1217 1162  734]
[ 497 1217  861]
[1365  532 1270]
[ 249   37  385 1217]
[953 836 915 841]
[857 672   5 722]
[  85   72 1365   85]
[1137  651 1217  774]
[672   5 871]
[1385]
[857]
[672   5 871 857]
[249  37 249]
[ 37 138 981]
[1380]
[1380  670  672  670]
[ 672  722 1290]
[857 236 670]
[672 722 192]
[1287  575  925]
[ 37 415 817]
[1228 1223  600]
[1217 1040  953]
[857]
[236 672   5  85]
[  72  236  651 1217]
[ 774 1221    5  722]
[  85 1110 1269  870]
[1137  870 1388  672]
[   5   85 1388  249]
[ 112 1045  672  596]
[   8 1302  422]
[1365   85 1137]
[857]
[ 857  857   37 1228]
[  37   37 1228   37]
[ 694 1343  672  670]
[1380]
[864 864 864 568]
[ 857 1118  844   37]
[  37 1228 1216 1216]
[1217  497 1216   37]
[249 385 672 735]
[ 722  101   85 1280]
[ 672    5  722 1217]
[ 121 1217  569 1217]
[1217  121 1216  416]
[ 689  651 1217  795]
[1290 1380  857 1380]
[672   5 722]
[1380  227  871]
[789  37 415 817]
[1228  882  881  925]
[ 600 1217 1040]
[690 851  93]
[341 16

[1390  387]
[1290  857 1118 1023]
[855]
[844 672   5]
[1389  509]
[855 815]
[1365  532  926]
[ 815  509 1003]
[ 861 1023]
[1385 1217 1003  861]
[857 236 985]
[1375]
[ 844 1232  670   85]
[1339 1225  672    5]
[ 85 575 300]
[789]
[672]
[672 596 722]
[532 925]
[1223  131  106 1271]
[236 841 996]
[118 672   5]
[106 722 646]
[1336 1374  600]
[722]
[ 532 1269  431]
[1281  835  382]
[236 672   5]
[ 996 1339]
[416 672 732]
[722  85  40]
[716  40]
[1385 1385  672    5]
[ 568  139 1380]
[857]
[857]
[1216    5  672]
[1334  672 1023]
[ 241 1217 1335]
[1380]
[857]
[1118 1232  861  670]
[  85 1073  735]
[722  85 479]
[1092 1365   85]
[ 85 840 118]
[ 85 827]
[ 85 731 840]
[1380  857  834]
[1118  672    5  575]
[834 574 388]
[112]
[574]
[1118  844 1336  600]
[1232  248 1336]
[ 584  143 1217]
[1315  180   99]
[857]
[273]
[857]
[1216    5  435]
[ 101  844 1336  600]
[  85 1381 1225]
[  37 1228 1217]
[ 863  861 1381]
[  37 1228  672    5]
[1217  863  861 1381]
[236 236 672 101]
[672   5 722  85]
[722  8

[870 763 478 722]
[ 193 1139 1283 1304]
[836]
[829]
[ 829 1395  845]
[ 390 1394 1320]
[  37  694 1347]
[861 844]
[  37 1228  672]
[   5 1232  861]
[855]
[ 857 1232  861  670]
[1217  510  861 1336]
[ 584 1217  927]
[ 861 1365 1217]
[1365 1217 1380]
[334]
[1232  670 1217]
[195 636  99]
[ 118 1232  861   37]
[415 817 694 646]
[1388  249 1059 1217]
[ 861 1216   37]
[1065 1378  236]
[ 672    5 1217]
[ 735  722   85 1055]
[522 118 672   5]
[ 672    5 1285  870]
[208]
[ 575 1380]
[1380   37 1228   37]
[ 694 1347  861]
[1380]
[1232  735  722]
[ 85 193  72]
[722  85]
[1217  716]
[ 193   72 1380]
[570 672]
[ 118 1232  861]
[670]
[864 672   5 106]
[ 722   85  646 1388]
[ 646 1388  885  672]
[672   5 722  85]
[ 614  236 1365 1119]
[1348  613 1059]
[ 722   85 1348]
[1139  425  118]
[672   5 672]
[  5  85 207]
[789]
[ 870 1217 1285  300]
[ 99 118 672   5]
[672   5 106 722]
[  85  614  236 1365]
[1139  859 1252]
[ 646 1388  493 1216]
[1217  727  118]
[1380  334]
[1232  670 1217  927]
[ 999 1365]
[126

[193 575 273]
[1246 1217 1023]
[193 575 273]
[1246 1217 1023]
[ 969  402 1246]
[1217  707  193]
[1110  402 1246]
[1217  707]
[ 207   63 1111  861]
[40]
[635]
[969 402]
[575 402]
[40]
[635]
[  23 1268]
[354]
[  72 1316]
[969 273]
[1003 1265]
[1324  800]
[193  63]
[1269 1300 1269]
[422 207]
[855 969  18]
[1279]
[1300  118  422 1269]
[18]
[855 273 207 697]
[1329 1329  193  273]
[1246 1217 1023  575]
[575]
[207  63]
[718 207 870]
[370 207]
[ 370  207 1111]
[ 855 1122 1388  100]
[1110  575  354 1039]
[1039  722   72]
[ 32 950]
[575 273 193]
[370 207  63]
[1300  118  422 1269]
[18]
[1300  118  422]
[18]
[1265]
[ 624  800 1324]
[402 969]
[402 575]
[1269  118 1145]
[ 857 1118  672    5]
[ 207  672    5 1118]
[670 722  85]
[ 72 236 670]
[722  85 905]
[1380]
[722  85 905]
[ 658 1380   37]
[ 249 1059  672]
[ 651 1217  658]
[1380  658]
[236 722 672   5]
[ 722 1385   85   72]
[1118 1221  670]
[722 516 727]
[  85 1216    5]
[1217  568  861]
[ 857 1216    5  334]
[505]
[1380 1216    5]
[ 85 568 861]


[ 722 1217   72]
[ 672    5 1217  813]
[ 855 1385]
[1346  670 1232  813]
[ 624  646 1388 1238]
[1389  602  672]
[  5  85 813]
[1380]
[904]
[1217 1110  904]
[1380 1110  904]
[857]
[ 672    5 1217]
[ 310 1166  229]
[ 672    5 1217]
[969 752]
[969 752 857]
[ 672    5 1217]
[871 752]
[1217  969  752]
[969 752]
[ 672    5 1217]
[871 752]
[ 672    5 1217]
[200 207 200]
[672   5 722 117]
[121 200 664 672]
[ 672    5 1217]
[1019   40]
[1385]
[ 672    5 1217]
[799 871 799]
[871 799]
[ 672    5 1217  396]
[871]
[1385]
[ 672    5 1217]
[ 728   72 1365]
[ 85 905 658]
[857 207]
[ 207  370  207 1380]
[ 672    5 1217  636]
[1217  969  636]
[1385]
[ 672    5 1217  813]
[ 672    5 1217  904]
[ 672    5 1217]
[1381  166]
[1381  166]
[ 672    5 1217]
[1110  417]
[ 672    5 1217]
[969  72]
[969  72]
[ 672    5 1217]
[207 166]
[1217  193  207  166]
[1385]
[ 672    5 1217]
[1040  166]
[ 672    5 1217]
[969 752]
[969 752]
[ 672    5 1217]
[871 752]
[1380]
[ 672    5 1217]
[1217  310  229]
[857]
[ 249 1059 12

[672 178]
[1384]
[1217  122  586  861]
[1217 1111  861]
[1217 1111  861]
[1221  672  670]
[ 855 1232  670 1217]
[1217 1003  800]
[1380]
[1221    5  863]
[ 861 1023]
[1380]
[1380]
[  37 1228 1118]
[1380]
[1023]
[744]
[1380]
[1217   76  861  672]
[  5 718 207]
[  85 1110]
[ 855  857 1380]
[857]
[1232  670 1217 1003]
[1217 1003  611  870]
[1344 1336  245  672]
[1380]
[118 672   5]
[ 863  861 1023]
[1380]
[ 37 415 817]
[1331 1246  483]
[1380]
[  37  582 1118]
[1380]
[ 37 415 817]
[1331 1246  483]
[  37 1235 1221 1334]
[ 85 831 777]
[ 855 1217  320]
[ 861 1217  207]
[672   5 863]
[1217  370  207  861]
[855]
[1217  207  207  861]
[1380  370  207]
[1380]
[ 855 1232  670 1217]
[ 524  894 1217]
[1217  969  861]
[969]
[1380]
[ 855 1217  575  573]
[855 857]
[1232  670 1217 1217]
[ 575  722 1110  999]
[ 118 1269  859 1252]
[1336    6  584]
[672 178]
[1380]
[1384]
[1217   80  861  871]
[ 855 1380]
[1217  122  267  588]
[1217 1217  195  861]
[1380]
[1217  122 1355]
[1217  122]
[1355]
[1355]
[1217 12

[1380]
[334]
[1389 1281]
[672   5 969  99]
[396 841 396]
[ 614 1107  614]
[ 670  672 1216  861]
[1385]
[857]
[ 855 1232  670  435]
[672   5  85]
[ 72 927  72]
[857]
[672   5 815]
[1281   99]
[1385]
[ 672    5 1217 1040]
[1073   37 1037 1388]
[1217  510 1240]
[  37 1249 1388]
[ 510 1240]
[857]
[969 354]
[1380]
[834]
[288]
[855]
[ 397 1388 1064  672]
[1380]
[ 37 397 817]
[553 124 843]
[ 855 1329  844]
[ 855 1380]
[ 672 1334  817]
[289 966]
[857]
[ 672    5 1389 1281]
[  99 1217  781]
[ 40 300 207]
[857]
[1389 1281]
[788]
[ 672    5 1003  651]
[300 118 672   5]
[722  85  18 722]
[1110   18  730]
[763  37 582]
[ 670 1216  339]
[1380]
[ 105 1023]
[640]
[ 855 1232  670  672]
[  5  85 258 207]
[1012  764  851   85]
[1183  951  870]
[ 85 394 219]
[  37  582   37 1065]
[1380]
[857]
[1380  339]
[ 672    5 1217 1040]
[1073   99  969  354]
[969 354]
[857]
[ 860   99 1217]
[781  40]
[1217 1073  670  651]
[1381  300 1217 1269]
[ 88  85 999]
[857]
[1380]
[672   5  85 273]
[ 241  674  300 1381]
[1003]

[259 118 722 118]
[ 143 1217  218  672]
[735 722 117]
[  47 1287  976]
[570 672]
[ 84 683]
[857 672   5]
[117 871 273]
[855 273]
[  37 1228  672    5]
[735 722  85 197]
[857]
[1217 1217  575  760]
[ 219   99  855 1217]
[575 760 219 722]
[1216   37  570]
[570 672]
[857]
[1290  672    5 1217]
[ 575 1339 1227  537]
[178 672   5]
[1161  537 1217]
[1252  118 1217]
[857]
[37]
[ 855 1388  570  672]
[1380]
[855]
[672]
[672   5 672   5]
[1217  747  747  735]
[722  85  82 870]
[735 722  85]
[ 402  870 1122]
[ 672  735 1246 1217]
[ 707 1089 1221  670]
[836 712 236 722]
[  85  996 1077]
[870  85 804]
[1290]
[1380]
[788]
[672   5  85  72]
[1365   85  774  506]
[672   5  85 575]
[774 506]
[1380]
[173]
[1217 1003  976   99]
[1003  396 1125]
[1003  396  570  672]
[857 672   5]
[1217  207  532]
[1138  799   99]
[857]
[ 855 1232  670]
[  85 1272  861]
[672 735 722]
[ 174 1221  131 1287]
[ 851 1219  118 1223]
[   4 1223  131]
[207]
[ 207  137 1341  722]
[1217  123  236  722]
[ 718  207  118 1223]
[735 64

[193 575 861]
[575]
[788 575 679]
[ 722 1206]
[1380]
[1217 1381  576]
[716  76]
[1380]
[1381]
[1380 1217 1381  576]
[1216 1336  415  817]
[ 694 1347  300  672]
[ 670  236 1217  861]
[1216  735  722]
[ 85  76 870]
[1384]
[  85  969 1269 1365]
[1269  859 1252]
[1217  193  575  861]
[1216  735  722]
[ 85 716  40]
[ 788 1217  927]
[ 841 1217  799]
[123 861 927]
[1380]
[1217 1110  207]
[ 861 1216  735]
[722  85 479]
[ 788 1217  927  800]
[1217 1110 1381  861]
[1216  735  722   85]
[166 870 716  46]
[1217  597]
[1217  207  597]
[207 597]
[ 602  651 1217]
[ 597 1380]
[602]
[857]
[1217  927  800]
[1217  871  800]
[ 118 1217  207  273]
[1217 1217  731]
[871 359]
[1217  193  575  636]
[788 193 716  72]
[ 118 1217  193  969]
[ 861 1216  596   85]
[1145  118   85]
[1269  145 1247]
[193 969]
[ 118 1217  871  800]
[1217  207  273]
[ 788 1380]
[1217  685  651]
[1217  207  685]
[1217 1110  207]
[716  72]
[ 788 1217  207 1269]
[1365   85 1145]
[1217  193  861]
[ 969 1388  765  870]
[1380  969]
[1217  8

[  5 672   5]
[1110 1110  207]
[855 672   5]
[1217 1110  861]
[ 101  857 1125]
[815 156]
[1385]
[1118  672    5   99]
[1217  976 1365 1287]
[1287 1270   89]
[855 857]
[561 102]
[ 672    5 1217]
[1040  248 1184]
[682]
[789]
[672   5  85  72]
[788]
[857]
[672   5 722 735]
[ 722   85  916 1365]
[ 85 597 722 193]
[1347  300]
[718 207 722]
[  85 1054  300]
[1380]
[1269 1365 1287  976]
[1365 1287 1270  783]
[ 788 1217 1040]
[1217  248 1184]
[789]
[101 672   5 672]
[   5 1217  799 1236]
[ 799  907  861 1217]
[ 259  861  193 1217]
[ 617 1003  300]
[ 672    5   85 1315]
[1110  927 1073 1365]
[789]
[722  85  40]
[690 851]
[1380]
[101 672   5  85]
[1110 1381 1073 1365]
[ 85 737 851 907]
[ 72 927  72]
[1110   72]
[72]
[101 672   5  85]
[  72  236   85 1224]
[ 861  118 1221    5]
[  85  905  143 1217]
[ 259  851 1217   72]
[ 857 1388  308   99]
[672   5 672   5]
[ 927  302  118 1380]
[118]
[1217  927  857]
[1380]
[ 855 1380   37 1059]
[1217 1381 1110]
[1381 1001 1073]
[1001 1073  836   37]
[ 415  8

[672   5 735 722]
[ 85 722  85 964]
[ 479  537 1217]
[1023  590 1089]
[1385 1295 1217 1136]
[1380 1216  861]
[1217 1136 1380]
[ 857 1232  670  651]
[1217 1252  707  337]
[1217  871   74]
[ 610  859 1252]
[ 851 1217 1136]
[ 788 1385]
[  99 1217  479]
[ 672    5  651 1217]
[570 672]
[1380 1388 1044  672]
[1217   74  610]
[871 861]
[1232 1240  672    5]
[ 651 1217 1023 1089]
[ 851 1217 1051]
[1380   37 1044  672]
[834]
[855 672   5]
[764  99]
[870 841 672]
[  5 101 857]
[1232  528  672    5]
[ 85 728 199 900]
[ 651 1217  774  851]
[1217 1051 1221    5]
[ 722   85 1221    5]
[722  85 799]
[1380]
[672   5 672]
[  5 722]
[1217  747  799]
[1380]
[ 682 1023 1329]
[836]
[1023  859 1252  851]
[ 672 1221  670   85]
[1119 1126  851  497]
[ 651   85   37 1374]
[1045  722   85  722]
[ 85 183 300]
[672 596 722]
[ 532 1091]
[1385]
[1380 1216  861]
[857]
[ 857 1118 1232  670]
[1217  871  556]
[ 672    5 1246 1217]
[1023  851 1217  254]
[1252  851 1217 1051]
[1217 1030]
[1217 1030]
[1217  479]
[ 844  67

[1294  672]
[857]
[855]
[1023  422 1023  337]
[ 422  422 1217  207]
[1217  207  354]
[857]
[1388  600   85]
[207  72]
[  88  672 1221]
[  5  85 575]
[ 396  870 1122]
[1384]
[1217  575  861 1380]
[1380]
[1381  354  651 1217]
[1023  422  337]
[672   5  85]
[399 354 857]
[1380]
[  85 1126  851  354]
[857 672   5]
[1301 1089]
[788]
[1023]
[789]
[1217 1048  804  236]
[672   5 672]
[  5 672   5]
[1324 1217  196]
[789]
[789]
[857]
[1217  927  197]
[1346  131 1388]
[927 197]
[1290]
[672   5 859]
[1217 1023]
[ 37 530 672]
[682  85 791]
[ 672    5 1170]
[ 855  857 1125]
[207]
[789]
[118 672   5 422]
[789]
[672 735 722  85]
[799 870 354]
[ 672    5 1217  707]
[101 857]
[1384]
[ 37 570 672]
[ 672    5 1217]
[370 207  72]
[118 422]
[1294 1217  804]
[857 672   5 370]
[207  72 646 672]
[ 5 85 72]
[1380]
[ 844  857 1388  600]
[ 722 1285  197  722]
[ 85 207 197]
[1285  197]
[1294 1216 1388  600]
[ 207 1225]
[  85  207 1225 1380]
[1384   37 1065  672]
[ 101  857 1217]
[ 707 1089  927]
[1217  196  847]
[

[1089  851  672]
[101 614 651]
[718 575]
[1217  349  573 1365]
[1217  719  575  300]
[1217  326 1268]
[651 207]
[1106  999 1365 1287]
[1270  651  969]
[1217  414]
[1178 1246 1307]
[  31 1371]
[611 871]
[ 871  870 1003]
[1388    4  301]
[ 26   5 712]
[651 871]
[ 583 1365   85]
[840 718 575]
[1217  894   97]
[651 720 575]
[1217  402  651 1339]
[575 300 651]
[ 192 1217  718]
[118 370 575]
[894  97]
[ 99 718 575]
[718 575]
[402]
[1217  573  651]
[718 575]
[1221  131]
[1217  720  851  577]
[1217  720  851  577]
[ 326 1268  651  207]
[1217  611  651 1003]
[ 26   5 710]
[651 871]
[1324  999 1365]
[1217 1023  119]
[1269  859 1252]
[614 575 861]
[1269 1365 1023  119]
[1269  861 1252]
[969]
[ 999 1380  969 1365]
[614 718 575]
[1217   72  651 1324]
[871 614]
[1217  349  573  651]
[1217  719  575]
[1217  720  851  575]
[1385]
[326 207]
[1217  614  651 1003]
[ 349  573  651 1217]
[720 851 577]
[1217  402  651  575]
[611 651 871]
[ 614  651 1003]
[ 349  573  651 1217]
[720 851 577]
[1217 1287 1270]


[ 532 1270  750]
[857 857 719]
[1214 1217  575]
[1380]
[672   5]
[1023]
[ 672    5  719 1214]
[1217  898  575]
[672   5  85]
[306 851 898]
[ 575  118 1381]
[857]
[670  85]
[857]
[672   5 719]
[1214  898  575]
[306 851 898]
[ 575  118 1381]
[1380]
[ 37   6 288 672]
[672   5 575]
[ 457 1073]
[857]
[898 575]
[672   5 969]
[651 300]
[ 672  735  722 1315]
[1393  859 1217 1252]
[118 735 722  85]
[597 851  85 692]
[ 672    5 1110]
[ 651 1101]
[836 672   5]
[ 195  651 1101]
[672   5  85 788]
[722  85 969 651]
[300 118 672  85]
[1317  548 1013 1073]
[857]
[672   5 207 651]
[300 718 207]
[672   5 746 851]
[1269  118   85 1145]
[1252 1269  118  859]
[1217 1023  741  337]
[ 670   85 1145]
[1232  861]
[1380]
[ 672    5   85 1104]
[207 651 300 841]
[ 465 1104  207]
[672   5  85 560]
[1073  537  741  451]
[ 118  859 1217 1252]
[ 670   85 1269 1380]
[857]
[1232  861]
[672   5 969 651]
[300 672   5]
[927 651 300]
[1110  651 1101]
[118 735 722  85]
[ 597  118 1220 1388]
[600  85 746 851]
[ 851 1118  753

[1136   46]
[ 859 1246 1389 1023]
[1269  118   85]
[ 667 1269]
[672   5  85  85]
[ 69 207 947]
[597 641 479]
[ 455  859 1217 1252]
[927]
[672   5  85]
[947 840]
[ 927  651 1217  259]
[ 84 683]
[ 859 1246 1389  218]
[1236  944 1270]
[575]
[1110  189   72]
[672   5  85  72]
[863  72]
[1324]
[ 859 1389 1252]
[  72 1365   85]
[ 944 1269]
[ 859 1217 1023  218]
[1302  422 1270]
[672   5 575 300]
[ 859 1246 1389]
[1023 1252]
[947 840 207]
[672   5 859]
[1389 1023  533]
[792  42 927]
[ 859 1246 1389]
[707 218]
[ 532  944 1270]
[1381]
[ 422 1221]
[ 532  944 1269]
[1380 1381  859 1246]
[1389  218  707]
[1343    5 1217  300]
[1381  300]
[1381  300  857 1125]
[1384]
[ 859 1246 1389  707]
[ 707  218 1217]
[ 207 1073 1347]
[ 722   85 1130]
[189  46]
[190  46]
[ 859 1246 1389 1252]
[  85 1269  118   85]
[1145 1003  300]
[1252 1023]
[672   5  85]
[  72 1324  300]
[  72 1365   85  944]
[1269  143 1217  259]
[1324]
[ 85 207 300]
[1380  207]
[  37 1152]
[855]
[855]
[  37    3 1125]
[ 115   37 1178]
[1246