In [1]:
import os
import platform
import sys

def get_project_root() -> str:
    system = platform.system()
    return r"D:\Users\tcshore\Documents\Projects\Tangrams\Data" if system == "Windows" else "/home/tshore/Projects/tangrams-restricted/Data"

infile_path = os.path.join(get_project_root(), "wordscores-inflected-small.tsv")
print("Will read file \"{}\".".format(infile_path), file=sys.stderr)

Will read file "D:\Users\tcshore\Documents\Projects\Tangrams\Data\wordscores-inflected-small.tsv".


In [2]:
import csv
import pandas as pd

RESULTS_FILE_CSV_DIALECT = csv.excel_tab
# NOTE: "category" dtype doesn't work with pandas-0.21.0 but does with pandas-0.21.1
__RESULTS_FILE_DTYPES = {"DYAD": "category", "ENTITY" : "category", "IS_TARGET": bool, "IS_OOV": bool,
				 "IS_INSTRUCTOR": bool, "SHAPE": "category", "ONLY_INSTRUCTOR": bool, "WEIGHT_BY_FREQ": bool}

def read_results_file(inpath: str, encoding: str) -> pd.DataFrame:
	print("Reading \"{}\" using encoding \"{}\".".format(inpath, encoding), file=sys.stderr)
	result = pd.read_csv(inpath, dialect=RESULTS_FILE_CSV_DIALECT, sep=RESULTS_FILE_CSV_DIALECT.delimiter,
						 float_precision="round_trip",
						 encoding=encoding, memory_map=True, dtype=__RESULTS_FILE_DTYPES)
	return result

cv_results = read_results_file(infile_path, "windows-1252")
print("Read {} cross-validation results for {} dyad(s).".format(cv_results.shape[0], cv_results["DYAD"].nunique()),
      file=sys.stderr)

Reading "D:\Users\tcshore\Documents\Projects\Tangrams\Data\wordscores-inflected-small.tsv" using encoding "windows-1252".
Read 67060 cross-validation results for 3 dyad(s).


In [3]:
OOV_LABEL = "__OOV__"
    
print("Replacing OOV words with label \"{}\".".format(OOV_LABEL), file=sys.stderr)
cv_results.loc[cv_results["IS_OOV"] == True, "WORD"] = OOV_LABEL

Replacing OOV words with label "__OOV__".


In [4]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# Create vocab before splitting training and testing DFs so that the word feature set is stable
print("Fitting one-hot encoder for vocabulary of size {}.".format(cv_results["WORD"].nunique()), file=sys.stderr)

# https://machinelearningmastery.com/how-to-one-hot-encode-sequence-data-in-python/
# integer encode
label_encoder = LabelEncoder()
vocab_labels = label_encoder.fit_transform(cv_results["WORD"])
cv_results["WORD_LABEL"] = vocab_labels
#print(vocab_labels)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
vocab_labels = vocab_labels.reshape(len(vocab_labels), 1)
onehot_encoder.fit(vocab_labels)
#assert onehot_encoder.n_values_ == len(vocab_words)
#vocab_onehot_encoded = onehot_encoder.fit_transform(vocab_labels)
#print(vocab_onehot_encoded)
# invert first example
#inverted = label_encoder.inverse_transform([np.argmax(vocab_onehot_encoded[0, :])])
#print(inverted)

Fitting one-hot encoder for vocabulary of size 249.


OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=False)

In [5]:
from typing import Tuple

import numpy as np

def find_target_ref_rows(df: pd.DataFrame) -> pd.DataFrame:
	result = df.loc[df["IS_TARGET"] == True]
	result_row_count = result.shape[0]
	complement_row_count = df.loc[~df.index.isin(result.index)].shape[0]
	assert result_row_count + complement_row_count == df.shape[0]
	print("Found {} nontarget rows and {} target rows. Ratio: {}".format(complement_row_count, result_row_count,
																		 complement_row_count / float(
																			 result_row_count)), file=sys.stderr)
	return result

def split_training_testing(df: pd.DataFrame, test_set_size : int) -> Tuple[pd.DataFrame, pd.DataFrame]:
	dyad_ids = df["DYAD"].unique()
	training_set_size = len(dyad_ids) - test_set_size
	if training_set_size < 1:
		raise ValueError("Desired test set size is {} but only {} dyads found.".format(test_set_size, len(dyad_ids)))
	else:
		training_set_dyads = frozenset(np.random.choice(dyad_ids, training_set_size))
		print("Training set dyads: {}".format(sorted(training_set_dyads)), file=sys.stderr)
		training_set_idxs = df["DYAD"].isin(training_set_dyads)
		training_set = df.loc[training_set_idxs]
		test_set = df.loc[~training_set_idxs]
		test_set_dyads = frozenset(test_set["DYAD"].unique())
		print("Test set dyads: {}".format(sorted(test_set_dyads)), file=sys.stderr)

		assert not frozenset(training_set["DYAD"].unique()).intersection(frozenset(test_set_dyads))
		return training_set, test_set
    
# https://stackoverflow.com/a/47815400/1391325
cv_results.sort_values("TOKEN_SEQ_ORDINALITY", inplace=True)
training_df, test_df = split_training_testing(cv_results, 1)
# Only train on "true" referents
training_df = find_target_ref_rows(training_df)

Training set dyads: ['20', '22']
Test set dyads: ['21']
Found 40489 nontarget rows and 2131 target rows. Ratio: 19.0


In [90]:
from collections import defaultdict
from typing import DefaultDict, Iterator, List

import keras.utils

class DataGeneratorFactory(object):

	def __init__(self, onehot_encoder):
		self.onehot_encoder = onehot_encoder

	@property
	def input_feature_count(self) -> int:
		word_features = self.onehot_encoder.n_values_[0]
		return word_features + 1

	@property
	def output_feature_count(self) -> int:
		return 1

	def __call__(self, df: pd.DataFrame) -> "TokenSequenceSequence":
		sequence_groups = df.groupby(
			("CROSS_VALIDATION_ITER", "DYAD", "ROUND", "UTT_START_TIME", "UTT_END_TIME", "ENTITY"), sort=False)
		print("Generating data for {} entity token sequence(s).".format(len(sequence_groups)), file=sys.stderr)
		seq_xy = sequence_groups.apply(self.__create_seq_xy)

		return TokenSequenceSequence(seq_xy)

	def __create_datapoint_x(self, row: pd.Series) -> Tuple[np.ndarray,]:
		# word_features = [0.0] * len(self.__vocab_idxs)
		# The features representing each individual vocabulary word are at the beginning of the feature vector
		# word_features[self.__vocab_idxs[row["WORD"]]] = 1.0
		# word_label = self.label_encoder.transform(row["WORD"])
		word_label = row["WORD_LABEL"]
		# print("Word label: {}".format(word_label), file=sys.stderr)
		# "OneHotEncoder.transform(..)" returns a matrix even if only a single value is passed to it, so get just the first (and only) row
		word_features = self.onehot_encoder.transform(word_label)[0]
		# print("Word features: {}".format(word_features), file=sys.stderr)
		# The word label for the one-hot encoding is that with the same index as the column that has a "1" value, i.e. the highest value in the vector of one-hot encoding values
		# inverse_label = np.argmax(word_features)
		# assert inverse_label == word_label
		# inverse_word = self.label_encoder.inverse_transform([inverse_label])
		# print("Inverse word label: {}".format(inverse_label), file=sys.stderr)
		is_instructor = 1.0 if row["IS_INSTRUCTOR"] else 0.0
		# is_target = 1.0 if row["IS_TARGET"] else 0.0
		other_features = np.array((is_instructor,))
		# result = word_features + other_features
		result = np.concatenate((word_features, other_features))
		# print("Created a vector of {} features.".format(len(result)), file=sys.stderr)
		# NOTE: Returning a tuple is a hack in order to return an instance of "np.ndarray" from "DataFrame.apply()"
		return result,

	def __create_seq_x_matrix(self, seq_df: pd.DataFrame) -> np.matrix:
		# NOTE: The returned tuples have to be unpacked outside of the "apply(..)" function
		vectors = seq_df.apply(self.__create_datapoint_x, axis=1)
		return np.matrix(tuple(vector[0] for vector in vectors))

	def __create_seq_xy(self, seq_df: pd.DataFrame) -> Tuple[np.matrix, np.ndarray]:
		x = self.__create_seq_x_matrix(seq_df)
		y = seq_df["PROBABILITY"].values
		return x, y


class TokenSequenceSequence(keras.utils.Sequence):
	"""
	A sequence (i.e. less confusingly a dataset) of token sequences, each of which is for a given distinct entity, i.e. possible referent.
	"""

	@staticmethod
	def __group_by_seq_len(seq_xy: pd.Series) -> DefaultDict[int, List[Tuple[np.matrix, np.ndarray]]]:
		result = defaultdict(list)
		for xy in seq_xy:
			seq_len = xy[0].shape[0]
			result[seq_len].append(xy)
		return result

	def __init__(self, seq_xy: pd.Series):
		len_dict = self.__group_by_seq_len(seq_xy)
		print("Created {} batches, one for each unique sequence length.".format(len(len_dict)), file=sys.stderr)
		self.seq_batches_by_len = tuple(len_dict.values())

	def __len__(self) -> int:
		return len(self.seq_batches_by_len)

	def __getitem__(self, idx: int) -> Tuple[np.ndarray, np.ndarray]:
		print("Getting batch idx {}.".format(idx), file=sys.stderr)
		batch = self.seq_batches_by_len[idx]
		seq_x = tuple(x for x, y in batch)
		x = np.asarray(seq_x)
		print("X shape: {}".format(x.shape), file=sys.stderr)
		seq_y = tuple(y for x, y in batch)
		y = np.asarray(seq_y)
		# y = np.expand_dims(y, axis=0)
		print("Y shape: {}".format(y.shape), file=sys.stderr)
		return x, y
    

print("Generating training data token sequences.", file=sys.stderr)
data_generator_factory = DataGeneratorFactory(onehot_encoder)
training_data_generator = data_generator_factory(training_df)

Generating training data token sequences.
Generating data for 291 entity token sequence(s).
Created 30 batches, one for each unique sequence length.


In [91]:
from keras.layers import Dense
from keras.layers import LSTM
from keras.models import Sequential

def create_model(input_feature_count: int, output_feature_count: int) -> Sequential:
	result = Sequential()
	# word_embeddings = Embedding(len(vocab), embedding_vector_length, input_length=max_review_length)
	# model.add(word_embeddings)
	# model.add(Embedding(top_words, embedding_vector_length, input_length=max_review_length))
	# input shape is a pair of (timesteps, features) <https://stackoverflow.com/a/44583784/1391325>
	input_shape = (None, input_feature_count)
	print("Input shape: {}".format(input_shape), file=sys.stderr)
	units = output_feature_count
	print("Units: {}".format(units), file=sys.stderr)
	lstm = LSTM(input_shape=input_shape, units=units, dropout=0.1, recurrent_dropout=0.1)
	# lstm = LSTM(batch_input_shape = training_x.shape, stateful = True, units=len(training_y.shape))
	result.add(lstm)
	result.add(Dense(units, activation='sigmoid'))
	result.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	print(result.summary())
	return result

model = create_model(data_generator_factory.input_feature_count, data_generator_factory.output_feature_count)

Input shape: (None, 250)
Units: 1


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_18 (LSTM)               (None, 1)                 1008      
_________________________________________________________________
dense_18 (Dense)             (None, 1)                 2         
Total params: 1,010
Trainable params: 1,010
Non-trainable params: 0
_________________________________________________________________
None


In [93]:
# train LSTM

epochs = 50
print("Training model using {} epoch(s).".format(epochs), file=sys.stderr)
for epoch in range(0, epochs):
    for x, y in training_data_generator:
        print(x)
        print(y)
#        model.fit(x, y, verbose=1)

#fit_generator(self, generator, steps_per_epoch=None, epochs=1, verbose=1, callbacks=None, validation_data=None, validation_steps=None, class_weight=None, max_queue_size=10, workers=1, use_multiprocessing=False, shuffle=True, initial_epoch=0)
training_history = model.fit_generator(training_data_generator, epochs=epochs, verbose=1)

# train LSTM <https://machinelearningmastery.com/memory-in-a-long-short-term-memory-network/>
#epochs = 5
#for i in range(epochs):
#    for seq_idx in range(0, training_x.shape[0]):
        #x = training_x[i]
#        x = training_x[0:31]
 #       x_oldshape = x.shape
 #       x_newshape = (-1, x_oldshape[0], x_oldshape[1])
        #x = np.reshape(x, x_newshape)
        #print("x.shape = {}".format(x.shape), file=sys.stderr)
        #y = training_y[i]
 #       y = training_y[0:31]
 #       y_oldshape = y.shape
 #       y_newshape = (-1, y_oldshape[0])
        #y = np.reshape(y, y_newshape)
        #print("y.shape = {}".format(y.shape), file=sys.stderr)
 #       model.fit(x, y, epochs=1, batch_size=1, verbose=1, shuffle=False)
 #       model.reset_states()
    
    

Training model using 50 epoch(s).
Getting batch idx 0.
X shape: (40, 1, 250)
Y shape: (40, 1)
Getting batch idx 1.
X shape: (34, 2, 250)
Y shape: (34, 2)
Getting batch idx 2.
X shape: (31, 3, 250)
Y shape: (31, 3)
Getting batch idx 3.
X shape: (27, 4, 250)
Y shape: (27, 4)
Getting batch idx 4.
X shape: (23, 5, 250)
Y shape: (23, 5)
Getting batch idx 5.
X shape: (15, 6, 250)
Y shape: (15, 6)
Getting batch idx 6.
X shape: (16, 7, 250)
Y shape: (16, 7)
Getting batch idx 7.
X shape: (13, 8, 250)
Y shape: (13, 8)
Getting batch idx 8.
X shape: (12, 9, 250)
Y shape: (12, 9)
Getting batch idx 9.
X shape: (6, 10, 250)
Y shape: (6, 10)
Getting batch idx 10.
X shape: (13, 11, 250)
Y shape: (13, 11)
Getting batch idx 11.
X shape: (6, 12, 250)
Y shape: (6, 12)
Getting batch idx 12.
X shape: (10, 13, 250)
Y shape: (10, 13)
Getting batch idx 13.
X shape: (9, 14, 250)
Y shape: (9, 14)
Getting batch idx 14.
X shape: (8, 15, 250)
Y shape: (8, 15)
Getting batch idx 15.
X shape: (2, 16, 250)
Y shape: (2, 

[[[ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]]

 ..., 
 [[ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]]]
[[ 0.5137191 ]
 [ 0.5137191 ]
 [ 0.5647695 ]
 [ 0.44514291]
 [ 0.44028732]
 [ 0.38828752]
 [ 0.47564182]
 [ 0.71831793]
 [ 0.58049927]
 [ 0.52894132]
 [ 0.52894132]
 [ 0.45475994]
 [ 0.597051  ]
 [ 0.52220411]
 [ 0.48243448]
 [ 0.74770382]
 [ 0.51527117]
 [ 0.60047067]
 [ 0.57118331]
 [ 0.5725783 ]
 [ 0.54496885]
 [ 0.47222936]
 [ 0.9981083 ]
 [ 0.56881635]
 [ 0.51571733]
 [ 0.99950667]
 [ 0.60098745]
 [ 0.58072271]
 [ 0.68307409]
 [ 0.41307047]
 [ 0.53400748]
 [ 0.56109571]
 [ 0.48225267]
 [ 0.5240197 ]
 [ 0.50188718]
 [ 0.35394939]
 [ 0.76189011]
 [ 0.55248304]
 [ 0.44252374]
 [ 0.49666817]]
[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1

Getting batch idx 26.
X shape: (1, 33, 250)
Y shape: (1, 33)
Getting batch idx 27.
X shape: (1, 34, 250)
Y shape: (1, 34)
Getting batch idx 28.
X shape: (1, 35, 250)
Y shape: (1, 35)
Getting batch idx 29.
X shape: (1, 40, 250)
Y shape: (1, 40)
Getting batch idx 30.
Getting batch idx 0.
X shape: (40, 1, 250)
Y shape: (40, 1)
Getting batch idx 1.
X shape: (34, 2, 250)
Y shape: (34, 2)
Getting batch idx 2.
X shape: (31, 3, 250)
Y shape: (31, 3)
Getting batch idx 3.
X shape: (27, 4, 250)
Y shape: (27, 4)
Getting batch idx 4.
X shape: (23, 5, 250)
Y shape: (23, 5)
Getting batch idx 5.
X shape: (15, 6, 250)
Y shape: (15, 6)
Getting batch idx 6.
X shape: (16, 7, 250)
Y shape: (16, 7)
Getting batch idx 7.
X shape: (13, 8, 250)
Y shape: (13, 8)
Getting batch idx 8.
X shape: (12, 9, 250)
Y shape: (12, 9)
Getting batch idx 9.
X shape: (6, 10, 250)
Y shape: (6, 10)
Getting batch idx 10.
X shape: (13, 11, 250)
Y shape: (13, 11)
Getting batch idx 11.
X shape: (6, 12, 250)
Y shape: (6, 12)
Getting ba

[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]]
[[  3.03693877e-12   4.52948606e-01   4.86254507e-01   4.92247795e-01
    4.91550637e-01   5.20068058e-01   4.08566377e-01   9.62644629e-01
    4.92247795e-01   4.91550637e-01   5.92635655e-37   5.20068058e-01
    4.08566377e-01   5.73953647e-01   5.73953647e-01   4.92247795e-01
    4.91550637e-01   5.20068058e-01   1.69099814e-12   5.18729758e-01
    4.86254507e-01   4.92247795e-01   4.91550637e-01   5.20068058e-01
    4.08566377e-01   9.62644629e-01   5.73953647e-01   4.52596671e-01
    4.91550637e-01   5.92635655e-37]]
[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]]
[[  4.56339955e-001   3.72811243e-001   4.59172956e-001 

Getting batch idx 22.
X shape: (4, 23, 250)
Y shape: (4, 23)
Getting batch idx 23.
X shape: (1, 24, 250)
Y shape: (1, 24)
Getting batch idx 24.
X shape: (2, 26, 250)
Y shape: (2, 26)
Getting batch idx 25.
X shape: (1, 30, 250)
Y shape: (1, 30)
Getting batch idx 26.
X shape: (1, 33, 250)
Y shape: (1, 33)
Getting batch idx 27.
X shape: (1, 34, 250)
Y shape: (1, 34)
Getting batch idx 28.
X shape: (1, 35, 250)
Y shape: (1, 35)
Getting batch idx 29.
X shape: (1, 40, 250)
Y shape: (1, 40)
Getting batch idx 30.
Getting batch idx 0.
X shape: (40, 1, 250)
Y shape: (40, 1)
Getting batch idx 1.
X shape: (34, 2, 250)
Y shape: (34, 2)
Getting batch idx 2.
X shape: (31, 3, 250)
Y shape: (31, 3)
Getting batch idx 3.
X shape: (27, 4, 250)
Y shape: (27, 4)
Getting batch idx 4.
X shape: (23, 5, 250)
Y shape: (23, 5)
Getting batch idx 5.
X shape: (15, 6, 250)
Y shape: (15, 6)
Getting batch idx 6.
X shape: (16, 7, 250)
Y shape: (16, 7)
Getting batch idx 7.
X shape: (13, 8, 250)
Y shape: (13, 8)
Getting ba

[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]]
[[  4.56252102e-01   5.23850311e-01   5.34277139e-01   5.14091635e-01
    5.66129657e-01   4.89093328e-01   3.59265955e-01   5.14091635e-01
    4.59444380e-01   5.14091635e-01   8.01420286e-01   5.57244208e-01
    5.14091635e-01   2.08387138e-41   4.89093328e-01   5.27065522e-01
    5.56213241e-01   5.27065522e-01   5.56213241e-01   9.55205918e-01
    5.13448109e-01   5.27065522e-01   5.56213241e-01   9.77169536e-01
    6.79190243e-01   8.23269222e-01]
 [  2.97838992e-01   4.90267585e-01   1.00000000e+00   6.05347816e-01
    5.41260796e-01   7.10681833e-01   5.87347899e-01   5.

Getting batch idx 21.
X shape: (2, 22, 250)
Y shape: (2, 22)
Getting batch idx 22.
X shape: (4, 23, 250)
Y shape: (4, 23)
Getting batch idx 23.
X shape: (1, 24, 250)
Y shape: (1, 24)
Getting batch idx 24.
X shape: (2, 26, 250)
Y shape: (2, 26)
Getting batch idx 25.
X shape: (1, 30, 250)
Y shape: (1, 30)
Getting batch idx 26.
X shape: (1, 33, 250)
Y shape: (1, 33)
Getting batch idx 27.
X shape: (1, 34, 250)
Y shape: (1, 34)
Getting batch idx 28.
X shape: (1, 35, 250)
Y shape: (1, 35)
Getting batch idx 29.
X shape: (1, 40, 250)
Y shape: (1, 40)
Getting batch idx 30.
Getting batch idx 0.
X shape: (40, 1, 250)
Y shape: (40, 1)
Getting batch idx 1.
X shape: (34, 2, 250)
Y shape: (34, 2)
Getting batch idx 2.
X shape: (31, 3, 250)
Y shape: (31, 3)
Getting batch idx 3.
X shape: (27, 4, 250)
Y shape: (27, 4)
Getting batch idx 4.
X shape: (23, 5, 250)
Y shape: (23, 5)
Getting batch idx 5.
X shape: (15, 6, 250)
Y shape: (15, 6)
Getting batch idx 6.
X shape: (16, 7, 250)
Y shape: (16, 7)
Getting b

[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]]
[[  4.56252102e-01   5.23850311e-01   5.34277139e-01   5.14091635e-01
    5.66129657e-01   4.89093328e-01   3.59265955e-01   5.14091635e-01
    4.59444380e-01   5.14091635e-01   8.01420286e-01   5.57244208e-01
    5.14091635e-01   2.08387138e-41   4.89093328e-01   5.27065522e-01
    5.56213241e-01   5.27065522e-01   5.56213241e-01   9.55205918e-01
    5.13448109e-01   5.27065522e-01   5.56213241e-01   9.77169536e-01
    6.79190243e-01   8.23269222e-01]
 [  2.97838992e-01   4.90267585e-01   1.00000000e+00   6.05347816e-01
    5.41260796e-01   7.10681833e-01   5.87347899e-01   5.

X shape: (10, 13, 250)
Y shape: (10, 13)
Getting batch idx 13.
X shape: (9, 14, 250)
Y shape: (9, 14)
Getting batch idx 14.
X shape: (8, 15, 250)
Y shape: (8, 15)
Getting batch idx 15.
X shape: (2, 16, 250)
Y shape: (2, 16)
Getting batch idx 16.
X shape: (1, 17, 250)
Y shape: (1, 17)
Getting batch idx 17.
X shape: (4, 18, 250)
Y shape: (4, 18)
Getting batch idx 18.
X shape: (4, 19, 250)
Y shape: (4, 19)
Getting batch idx 19.
X shape: (2, 20, 250)
Y shape: (2, 20)
Getting batch idx 20.
X shape: (1, 21, 250)
Y shape: (1, 21)
Getting batch idx 21.
X shape: (2, 22, 250)
Y shape: (2, 22)
Getting batch idx 22.
X shape: (4, 23, 250)
Y shape: (4, 23)
Getting batch idx 23.
X shape: (1, 24, 250)
Y shape: (1, 24)
Getting batch idx 24.
X shape: (2, 26, 250)
Y shape: (2, 26)
Getting batch idx 25.
X shape: (1, 30, 250)
Y shape: (1, 30)
Getting batch idx 26.
X shape: (1, 33, 250)
Y shape: (1, 33)
Getting batch idx 27.
X shape: (1, 34, 250)
Y shape: (1, 34)
Getting batch idx 28.
X shape: (1, 35, 250)


[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 ..., 
 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  

Getting batch idx 12.
X shape: (10, 13, 250)
Y shape: (10, 13)
Getting batch idx 13.
X shape: (9, 14, 250)
Y shape: (9, 14)
Getting batch idx 14.
X shape: (8, 15, 250)
Y shape: (8, 15)
Getting batch idx 15.
X shape: (2, 16, 250)
Y shape: (2, 16)
Getting batch idx 16.
X shape: (1, 17, 250)
Y shape: (1, 17)
Getting batch idx 17.
X shape: (4, 18, 250)
Y shape: (4, 18)
Getting batch idx 18.
X shape: (4, 19, 250)
Y shape: (4, 19)
Getting batch idx 19.
X shape: (2, 20, 250)
Y shape: (2, 20)
Getting batch idx 20.
X shape: (1, 21, 250)
Y shape: (1, 21)
Getting batch idx 21.
X shape: (2, 22, 250)
Y shape: (2, 22)
Getting batch idx 22.
X shape: (4, 23, 250)
Y shape: (4, 23)
Getting batch idx 23.
X shape: (1, 24, 250)
Y shape: (1, 24)
Getting batch idx 24.
X shape: (2, 26, 250)
Y shape: (2, 26)
Getting batch idx 25.
X shape: (1, 30, 250)
Y shape: (1, 30)
Getting batch idx 26.
X shape: (1, 33, 250)
Y shape: (1, 33)
Getting batch idx 27.
X shape: (1, 34, 250)
Y shape: (1, 34)
Getting batch idx 28.


[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 ..., 
 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  

Getting batch idx 3.
X shape: (27, 4, 250)
Y shape: (27, 4)
Getting batch idx 4.
X shape: (23, 5, 250)
Y shape: (23, 5)
Getting batch idx 5.
X shape: (15, 6, 250)
Y shape: (15, 6)
Getting batch idx 6.
X shape: (16, 7, 250)
Y shape: (16, 7)
Getting batch idx 7.
X shape: (13, 8, 250)
Y shape: (13, 8)
Getting batch idx 8.
X shape: (12, 9, 250)
Y shape: (12, 9)
Getting batch idx 9.
X shape: (6, 10, 250)
Y shape: (6, 10)
Getting batch idx 10.
X shape: (13, 11, 250)
Y shape: (13, 11)
Getting batch idx 11.
X shape: (6, 12, 250)
Y shape: (6, 12)
Getting batch idx 12.
X shape: (10, 13, 250)
Y shape: (10, 13)
Getting batch idx 13.
X shape: (9, 14, 250)
Y shape: (9, 14)
Getting batch idx 14.
X shape: (8, 15, 250)
Y shape: (8, 15)
Getting batch idx 15.
X shape: (2, 16, 250)
Y shape: (2, 16)
Getting batch idx 16.
X shape: (1, 17, 250)
Y shape: (1, 17)
Getting batch idx 17.
X shape: (4, 18, 250)
Y shape: (4, 18)
Getting batch idx 18.
X shape: (4, 19, 250)
Y shape: (4, 19)
Getting batch idx 19.
X sha


[[  6.29178798e-001   4.48419794e-001   4.90061338e-001   3.47877611e-015]
 [  4.47614774e-001   4.84389616e-001   5.74961554e-001   6.79124512e-001]
 [  5.97050998e-001   4.67139113e-001   4.98067054e-001   4.98067054e-001]
 [  7.05146046e-001   5.56144602e-001   5.82494121e-001   5.20841711e-001]
 [  5.22080827e-001   9.36814951e-001   5.29780398e-001   1.00000000e+000]
 [  4.19859869e-001   7.38953393e-001   8.58263304e-001   6.57908398e-001]
 [  4.76806017e-001   7.28544281e-001   7.61615953e-001   5.91109852e-001]
 [  4.62228182e-001   7.77664735e-001   7.52486945e-001   5.78532936e-001]
 [  4.61484487e-001   7.44282563e-001   7.52562436e-001   5.98779182e-001]
 [  6.43126284e-001   7.60777504e-001   5.53621832e-001   2.48266371e-002]
 [  4.85761977e-001   6.09941477e-001   5.87011108e-001   4.61946185e-017]
 [  3.80143121e-001   4.99924392e-001   4.97637225e-001   8.87611976e-001]
 [  5.24885228e-001   7.96660589e-001   7.00718206e-001   9.53530374e-001]
 [  4.91841546e-001   9.


X shape: (1, 30, 250)
Y shape: (1, 30)
Getting batch idx 26.
X shape: (1, 33, 250)
Y shape: (1, 33)
Getting batch idx 27.
X shape: (1, 34, 250)
Y shape: (1, 34)
Getting batch idx 28.
X shape: (1, 35, 250)
Y shape: (1, 35)
Getting batch idx 29.
X shape: (1, 40, 250)
Y shape: (1, 40)
Getting batch idx 30.
Getting batch idx 0.
X shape: (40, 1, 250)
Y shape: (40, 1)
Getting batch idx 1.
X shape: (34, 2, 250)
Y shape: (34, 2)
Getting batch idx 2.
X shape: (31, 3, 250)
Y shape: (31, 3)
Getting batch idx 3.
X shape: (27, 4, 250)
Y shape: (27, 4)
Getting batch idx 4.
X shape: (23, 5, 250)
Y shape: (23, 5)
Getting batch idx 5.
X shape: (15, 6, 250)
Y shape: (15, 6)
Getting batch idx 6.
X shape: (16, 7, 250)
Y shape: (16, 7)
Getting batch idx 7.
X shape: (13, 8, 250)
Y shape: (13, 8)
Getting batch idx 8.
X shape: (12, 9, 250)
Y shape: (12, 9)
Getting batch idx 9.
X shape: (6, 10, 250)
Y shape: (6, 10)
Getting batch idx 10.
X shape: (13, 11, 250)
Y shape: (13, 11)
Getting batch idx 11.
X shape: 

[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]]
[[  3.03693877e-12   4.52948606e-01   4.86254507e-01   4.92247795e-01
    4.91550637e-01   5.20068058e-01   4.08566377e-01   9.62644629e-01
    4.92247795e-01   4.91550637e-01   5.92635655e-37   5.20068058e-01
    4.08566377e-01   5.73953647e-01   5.73953647e-01   4.92247795e-01
    4.91550637e-01   5.20068058e-01   1.69099814e-12   5.18729758e-01
    4.86254507e-01   4.92247795e-01   4.91550637e-01   5.20068058e-01
    4.08566377e-01   9.62644629e-01   5.73953647e-01   4.52596671e-01
    4.91550637e-01   5.92635655e-37]]
[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]]
[[  4.56339955e-001   3.72811243e-001   4.59172956e-001 

X shape: (8, 15, 250)
Y shape: (8, 15)
Getting batch idx 15.
X shape: (2, 16, 250)
Y shape: (2, 16)
Getting batch idx 16.
X shape: (1, 17, 250)
Y shape: (1, 17)
Getting batch idx 17.
X shape: (4, 18, 250)
Y shape: (4, 18)
Getting batch idx 18.
X shape: (4, 19, 250)
Y shape: (4, 19)
Getting batch idx 19.
X shape: (2, 20, 250)
Y shape: (2, 20)
Getting batch idx 20.
X shape: (1, 21, 250)
Y shape: (1, 21)
Getting batch idx 21.
X shape: (2, 22, 250)
Y shape: (2, 22)
Getting batch idx 22.
X shape: (4, 23, 250)
Y shape: (4, 23)
Getting batch idx 23.
X shape: (1, 24, 250)
Y shape: (1, 24)
Getting batch idx 24.
X shape: (2, 26, 250)
Y shape: (2, 26)
Getting batch idx 25.
X shape: (1, 30, 250)
Y shape: (1, 30)
Getting batch idx 26.
X shape: (1, 33, 250)
Y shape: (1, 33)
Getting batch idx 27.
X shape: (1, 34, 250)
Y shape: (1, 34)
Getting batch idx 28.
X shape: (1, 35, 250)
Y shape: (1, 35)
Getting batch idx 29.
X shape: (1, 40, 250)
Y shape: (1, 40)
Getting batch idx 30.
Getting batch idx 0.
X s

[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 ..., 
 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  

 [  3.45552116e-001   1.28162013e-001   1.81551550e-001   4.22694306e-001]]
[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 ..., 
 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. .

Getting batch idx 4.
X shape: (23, 5, 250)
Y shape: (23, 5)
Getting batch idx 5.
X shape: (15, 6, 250)
Y shape: (15, 6)
Getting batch idx 6.
X shape: (16, 7, 250)
Y shape: (16, 7)
Getting batch idx 7.
X shape: (13, 8, 250)
Y shape: (13, 8)
Getting batch idx 8.
X shape: (12, 9, 250)
Y shape: (12, 9)
Getting batch idx 9.
X shape: (6, 10, 250)
Y shape: (6, 10)
Getting batch idx 10.
X shape: (13, 11, 250)
Y shape: (13, 11)
Getting batch idx 11.
X shape: (6, 12, 250)
Y shape: (6, 12)
Getting batch idx 12.
X shape: (10, 13, 250)
Y shape: (10, 13)
Getting batch idx 13.
X shape: (9, 14, 250)
Y shape: (9, 14)
Getting batch idx 14.
X shape: (8, 15, 250)
Y shape: (8, 15)
Getting batch idx 15.
X shape: (2, 16, 250)
Y shape: (2, 16)
Getting batch idx 16.
X shape: (1, 17, 250)
Y shape: (1, 17)
Getting batch idx 17.
X shape: (4, 18, 250)
Y shape: (4, 18)
Getting batch idx 18.
X shape: (4, 19, 250)
Y shape: (4, 19)
Getting batch idx 19.
X shape: (2, 20, 250)
Y shape: (2, 20)
Getting batch idx 20.
X sh

[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]]
[[  5.14905843e-01   5.23844034e-01   5.41047995e-01   5.14905843e-01
    5.23844034e-01   4.77458397e-01   5.41636214e-01   1.15540706e-08
    5.41047995e-01   1.85309


X shape: (4, 19, 250)
Y shape: (4, 19)
Getting batch idx 19.
X shape: (2, 20, 250)
Y shape: (2, 20)
Getting batch idx 20.
X shape: (1, 21, 250)
Y shape: (1, 21)
Getting batch idx 21.
X shape: (2, 22, 250)
Y shape: (2, 22)
Getting batch idx 22.
X shape: (4, 23, 250)
Y shape: (4, 23)
Getting batch idx 23.
X shape: (1, 24, 250)
Y shape: (1, 24)
Getting batch idx 24.
X shape: (2, 26, 250)
Y shape: (2, 26)
Getting batch idx 25.
X shape: (1, 30, 250)
Y shape: (1, 30)
Getting batch idx 26.
X shape: (1, 33, 250)
Y shape: (1, 33)
Getting batch idx 27.
X shape: (1, 34, 250)
Y shape: (1, 34)
Getting batch idx 28.
X shape: (1, 35, 250)
Y shape: (1, 35)
Getting batch idx 29.
X shape: (1, 40, 250)
Y shape: (1, 40)
Getting batch idx 30.
Getting batch idx 0.
X shape: (40, 1, 250)
Y shape: (40, 1)
Getting batch idx 1.
X shape: (34, 2, 250)
Y shape: (34, 2)
Getting batch idx 2.
X shape: (31, 3, 250)
Y shape: (31, 3)
Getting batch idx 3.
X shape: (27, 4, 250)
Y shape: (27, 4)
Getting batch idx 4.
X shap

[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0. 

Getting batch idx 13.
X shape: (9, 14, 250)
Y shape: (9, 14)
Getting batch idx 14.
X shape: (8, 15, 250)
Y shape: (8, 15)
Getting batch idx 15.
X shape: (2, 16, 250)
Y shape: (2, 16)
Getting batch idx 16.
X shape: (1, 17, 250)
Y shape: (1, 17)
Getting batch idx 17.
X shape: (4, 18, 250)
Y shape: (4, 18)
Getting batch idx 18.
X shape: (4, 19, 250)
Y shape: (4, 19)
Getting batch idx 19.
X shape: (2, 20, 250)
Y shape: (2, 20)
Getting batch idx 20.
X shape: (1, 21, 250)
Y shape: (1, 21)
Getting batch idx 21.
X shape: (2, 22, 250)
Y shape: (2, 22)
Getting batch idx 22.
X shape: (4, 23, 250)
Y shape: (4, 23)
Getting batch idx 23.
X shape: (1, 24, 250)
Y shape: (1, 24)
Getting batch idx 24.
X shape: (2, 26, 250)
Y shape: (2, 26)
Getting batch idx 25.
X shape: (1, 30, 250)
Y shape: (1, 30)
Getting batch idx 26.
X shape: (1, 33, 250)
Y shape: (1, 33)
Getting batch idx 27.
X shape: (1, 34, 250)
Y shape: (1, 34)
Getting batch idx 28.
X shape: (1, 35, 250)
Y shape: (1, 35)
Getting batch idx 29.
X 


[[  4.22574044e-01   3.72593803e-01]
 [  2.70288292e-01   3.92889100e-01]
 [  5.47460416e-01   5.49895107e-01]
 [  4.32348094e-01   4.82146261e-01]
 [  4.42506872e-01   5.04227051e-01]
 [  7.46090764e-01   7.64091753e-01]
 [  3.76386940e-12   4.76899057e-01]
 [  6.25854572e-01   5.06109150e-01]
 [  4.84566228e-01   9.02570018e-81]
 [  5.24858321e-01   5.78214275e-01]
 [  5.07836571e-01   9.86554359e-01]
 [  5.28814348e-01   9.75204607e-01]
 [  4.96916700e-01   9.98403724e-01]
 [  6.38718174e-01   4.74859981e-01]
 [  4.44066667e-01   9.45285965e-01]
 [  7.24384939e-01   9.96944222e-01]
 [  7.80812032e-01   9.85918125e-01]
 [  8.36953255e-01   9.70383909e-01]
 [  5.01045000e-01   5.01045000e-01]
 [  7.83555591e-01   9.88671921e-01]
 [  7.37085344e-01   4.22216814e-01]
 [  8.61090216e-01   9.75877933e-01]
 [  9.43216709e-01   5.00090818e-01]
 [  4.33361247e-01   8.75756655e-01]
 [  8.31170286e-01   9.89349118e-01]
 [  1.00000000e+00   9.52058657e-01]
 [  1.00000000e+00   9.58908395e-01]


X shape: (12, 9, 250)
Y shape: (12, 9)
Getting batch idx 9.
X shape: (6, 10, 250)
Y shape: (6, 10)
Getting batch idx 10.
X shape: (13, 11, 250)
Y shape: (13, 11)
Getting batch idx 11.
X shape: (6, 12, 250)
Y shape: (6, 12)
Getting batch idx 12.
X shape: (10, 13, 250)
Y shape: (10, 13)
Getting batch idx 13.
X shape: (9, 14, 250)
Y shape: (9, 14)
Getting batch idx 14.
X shape: (8, 15, 250)
Y shape: (8, 15)
Getting batch idx 15.
X shape: (2, 16, 250)
Y shape: (2, 16)
Getting batch idx 16.
X shape: (1, 17, 250)
Y shape: (1, 17)
Getting batch idx 17.
X shape: (4, 18, 250)
Y shape: (4, 18)
Getting batch idx 18.
X shape: (4, 19, 250)
Y shape: (4, 19)
Getting batch idx 19.
X shape: (2, 20, 250)
Y shape: (2, 20)
Getting batch idx 20.
X shape: (1, 21, 250)
Y shape: (1, 21)
Getting batch idx 21.
X shape: (2, 22, 250)
Y shape: (2, 22)
Getting batch idx 22.
X shape: (4, 23, 250)
Y shape: (4, 23)
Getting batch idx 23.
X shape: (1, 24, 250)
Y shape: (1, 24)
Getting batch idx 24.
X shape: (2, 26, 250)


[[ 0.54529581  0.48029786  0.45459017  0.34273708  0.46878797  0.7458672
   0.70705056  0.50595673  0.46878797  0.60298035  0.25788556  0.41489312
   0.39452695  0.45455907  0.79787345  0.48029786  0.45459017  0.83170692]
 [ 0.520149    0.52243307  0.94952767  0.47088265  0.62093073  0.520149
   0.520149    0.52243307  0.75535562  0.78853516  0.58529175  0.32899189
   0.58529175  0.96592853  0.84892342  0.62093073  0.58529175  0.52243307]
 [ 0.68307409  0.50524237  0.02408431  0.33344289  0.57812684  0.02408431
   0.9361516   0.51730307  0.58456581  0.54402009  0.50524237  0.99978255
   0.48864395  0.2863746   0.30287385  0.43411382  0.45011954  0.51730307]
 [ 0.52185154  0.5167031   0.52612143  0.54918558  0.64285172  0.70199362
   0.55098499  0.54918558  0.77863887  0.54918558  0.75499679  0.37926381
   0.57915606  0.59857339  0.59858635  0.69752024  0.55099426  0.84185445]]
[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  

Getting batch idx 22.
X shape: (4, 23, 250)
Y shape: (4, 23)
Getting batch idx 23.
X shape: (1, 24, 250)
Y shape: (1, 24)
Getting batch idx 24.
X shape: (2, 26, 250)
Y shape: (2, 26)
Getting batch idx 25.
X shape: (1, 30, 250)
Y shape: (1, 30)
Getting batch idx 26.
X shape: (1, 33, 250)
Y shape: (1, 33)
Getting batch idx 27.
X shape: (1, 34, 250)
Y shape: (1, 34)
Getting batch idx 28.
X shape: (1, 35, 250)
Y shape: (1, 35)
Getting batch idx 29.
X shape: (1, 40, 250)
Y shape: (1, 40)
Getting batch idx 30.
Getting batch idx 0.
X shape: (40, 1, 250)
Y shape: (40, 1)
Getting batch idx 1.
X shape: (34, 2, 250)
Y shape: (34, 2)
Getting batch idx 2.
X shape: (31, 3, 250)
Y shape: (31, 3)
Getting batch idx 3.
X shape: (27, 4, 250)
Y shape: (27, 4)
Getting batch idx 4.
X shape: (23, 5, 250)
Y shape: (23, 5)
Getting batch idx 5.
X shape: (15, 6, 250)
Y shape: (15, 6)
Getting batch idx 6.
X shape: (16, 7, 250)
Y shape: (16, 7)
Getting batch idx 7.
X shape: (13, 8, 250)
Y shape: (13, 8)
Getting ba

[[  4.27258367e-01   4.44054508e-01   4.52306699e-01   7.10480060e-01
    6.55547628e-01   9.53804318e-01]
 [  4.41142271e-01   4.63235230e-01   4.63825564e-01   7.29671192e-01
    6.50344546e-01   9.64395859e-01]
 [  5.28941319e-01   5.79425279e-01   9.35325439e-01   7.84301028e-01
    4.76064320e-01   9.92150921e-11]
 [  6.61465781e-01   5.81352844e-01   4.81867235e-01   4.48175468e-01
    5.65083951e-01   8.78805398e-10]
 [  4.60150787e-01   4.80350943e-01   4.04274331e-01   6.65918812e-01
    4.19245283e-01   9.37877631e-01]
 [  5.17321198e-01   6.94782302e-01   1.25166550e-01   4.22451428e-01
    5.17321198e-01   6.44915433e-01]
 [  5.25573730e-01   6.78853142e-15   8.53325022e-01   8.38902280e-01
    6.41672335e-01   6.61358284e-01]
 [  5.48097502e-01   4.25330617e-25   8.73585012e-01   9.23687128e-01
    5.48097502e-01   9.38715357e-01]
 [  4.82162571e-01   7.92331016e-01   9.95312621e-01   4.52640787e-08
    4.67855733e-01   4.56124314e-01]
 [  5.14516549e-01   9.77187755e-01  

X shape: (8, 15, 250)
Y shape: (8, 15)
Getting batch idx 15.
X shape: (2, 16, 250)
Y shape: (2, 16)
Getting batch idx 16.
X shape: (1, 17, 250)
Y shape: (1, 17)
Getting batch idx 17.
X shape: (4, 18, 250)
Y shape: (4, 18)
Getting batch idx 18.
X shape: (4, 19, 250)
Y shape: (4, 19)
Getting batch idx 19.
X shape: (2, 20, 250)
Y shape: (2, 20)
Getting batch idx 20.
X shape: (1, 21, 250)
Y shape: (1, 21)
Getting batch idx 21.
X shape: (2, 22, 250)
Y shape: (2, 22)
Getting batch idx 22.
X shape: (4, 23, 250)
Y shape: (4, 23)
Getting batch idx 23.
X shape: (1, 24, 250)
Y shape: (1, 24)
Getting batch idx 24.
X shape: (2, 26, 250)
Y shape: (2, 26)
Getting batch idx 25.
X shape: (1, 30, 250)
Y shape: (1, 30)
Getting batch idx 26.
X shape: (1, 33, 250)
Y shape: (1, 33)
Getting batch idx 27.
X shape: (1, 34, 250)
Y shape: (1, 34)
Getting batch idx 28.
X shape: (1, 35, 250)
Y shape: (1, 35)
Getting batch idx 29.
X shape: (1, 40, 250)
Y shape: (1, 40)
Getting batch idx 30.
Getting batch idx 0.
X s


[[ 0.5137191 ]
 [ 0.5137191 ]
 [ 0.5647695 ]
 [ 0.44514291]
 [ 0.44028732]
 [ 0.38828752]
 [ 0.47564182]
 [ 0.71831793]
 [ 0.58049927]
 [ 0.52894132]
 [ 0.52894132]
 [ 0.45475994]
 [ 0.597051  ]
 [ 0.52220411]
 [ 0.48243448]
 [ 0.74770382]
 [ 0.51527117]
 [ 0.60047067]
 [ 0.57118331]
 [ 0.5725783 ]
 [ 0.54496885]
 [ 0.47222936]
 [ 0.9981083 ]
 [ 0.56881635]
 [ 0.51571733]
 [ 0.99950667]
 [ 0.60098745]
 [ 0.58072271]
 [ 0.68307409]
 [ 0.41307047]
 [ 0.53400748]
 [ 0.56109571]
 [ 0.48225267]
 [ 0.5240197 ]
 [ 0.50188718]
 [ 0.35394939]
 [ 0.76189011]
 [ 0.55248304]
 [ 0.44252374]
 [ 0.49666817]]
[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]]

 ..., 
 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...

X shape: (6, 10, 250)
Y shape: (6, 10)
Getting batch idx 10.
X shape: (13, 11, 250)
Y shape: (13, 11)
Getting batch idx 11.
X shape: (6, 12, 250)
Y shape: (6, 12)
Getting batch idx 12.
X shape: (10, 13, 250)
Y shape: (10, 13)
Getting batch idx 13.
X shape: (9, 14, 250)
Y shape: (9, 14)
Getting batch idx 14.
X shape: (8, 15, 250)
Y shape: (8, 15)
Getting batch idx 15.
X shape: (2, 16, 250)
Y shape: (2, 16)
Getting batch idx 16.
X shape: (1, 17, 250)
Y shape: (1, 17)
Getting batch idx 17.
X shape: (4, 18, 250)
Y shape: (4, 18)
Getting batch idx 18.
X shape: (4, 19, 250)
Y shape: (4, 19)
Getting batch idx 19.
X shape: (2, 20, 250)
Y shape: (2, 20)
Getting batch idx 20.
X shape: (1, 21, 250)
Y shape: (1, 21)
Getting batch idx 21.
X shape: (2, 22, 250)
Y shape: (2, 22)
Getting batch idx 22.
X shape: (4, 23, 250)
Y shape: (4, 23)
Getting batch idx 23.
X shape: (1, 24, 250)
Y shape: (1, 24)
Getting batch idx 24.
X shape: (2, 26, 250)
Y shape: (2, 26)
Getting batch idx 25.
X shape: (1, 30, 250


[[  4.22574044e-01   3.72593803e-01]
 [  2.70288292e-01   3.92889100e-01]
 [  5.47460416e-01   5.49895107e-01]
 [  4.32348094e-01   4.82146261e-01]
 [  4.42506872e-01   5.04227051e-01]
 [  7.46090764e-01   7.64091753e-01]
 [  3.76386940e-12   4.76899057e-01]
 [  6.25854572e-01   5.06109150e-01]
 [  4.84566228e-01   9.02570018e-81]
 [  5.24858321e-01   5.78214275e-01]
 [  5.07836571e-01   9.86554359e-01]
 [  5.28814348e-01   9.75204607e-01]
 [  4.96916700e-01   9.98403724e-01]
 [  6.38718174e-01   4.74859981e-01]
 [  4.44066667e-01   9.45285965e-01]
 [  7.24384939e-01   9.96944222e-01]
 [  7.80812032e-01   9.85918125e-01]
 [  8.36953255e-01   9.70383909e-01]
 [  5.01045000e-01   5.01045000e-01]
 [  7.83555591e-01   9.88671921e-01]
 [  7.37085344e-01   4.22216814e-01]
 [  8.61090216e-01   9.75877933e-01]
 [  9.43216709e-01   5.00090818e-01]
 [  4.33361247e-01   8.75756655e-01]
 [  8.31170286e-01   9.89349118e-01]
 [  1.00000000e+00   9.52058657e-01]
 [  1.00000000e+00   9.58908395e-01]


X shape: (6, 10, 250)
Y shape: (6, 10)
Getting batch idx 10.
X shape: (13, 11, 250)
Y shape: (13, 11)
Getting batch idx 11.
X shape: (6, 12, 250)
Y shape: (6, 12)
Getting batch idx 12.
X shape: (10, 13, 250)
Y shape: (10, 13)
Getting batch idx 13.
X shape: (9, 14, 250)
Y shape: (9, 14)
Getting batch idx 14.
X shape: (8, 15, 250)
Y shape: (8, 15)
Getting batch idx 15.
X shape: (2, 16, 250)
Y shape: (2, 16)
Getting batch idx 16.
X shape: (1, 17, 250)
Y shape: (1, 17)
Getting batch idx 17.
X shape: (4, 18, 250)
Y shape: (4, 18)
Getting batch idx 18.
X shape: (4, 19, 250)
Y shape: (4, 19)
Getting batch idx 19.
X shape: (2, 20, 250)
Y shape: (2, 20)
Getting batch idx 20.
X shape: (1, 21, 250)
Y shape: (1, 21)
Getting batch idx 21.
X shape: (2, 22, 250)
Y shape: (2, 22)
Getting batch idx 22.
X shape: (4, 23, 250)
Y shape: (4, 23)
Getting batch idx 23.
X shape: (1, 24, 250)
Y shape: (1, 24)
Getting batch idx 24.
X shape: (2, 26, 250)
Y shape: (2, 26)
Getting batch idx 25.
X shape: (1, 30, 250

[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]]
[[ 0.54529581  0.48029786  0.45459017  0.34273708  0.46878797  0.7458672
   0.70705056  0.50595673  0.46878797  0.60298035  0.25788556  0.41489312
   0.39452695  0.4545


X shape: (15, 6, 250)
Y shape: (15, 6)
Getting batch idx 6.
X shape: (16, 7, 250)
Y shape: (16, 7)
Getting batch idx 7.
X shape: (13, 8, 250)
Y shape: (13, 8)
Getting batch idx 8.
X shape: (12, 9, 250)
Y shape: (12, 9)
Getting batch idx 9.
X shape: (6, 10, 250)
Y shape: (6, 10)
Getting batch idx 10.
X shape: (13, 11, 250)
Y shape: (13, 11)
Getting batch idx 11.
X shape: (6, 12, 250)
Y shape: (6, 12)
Getting batch idx 12.
X shape: (10, 13, 250)
Y shape: (10, 13)
Getting batch idx 13.
X shape: (9, 14, 250)
Y shape: (9, 14)
Getting batch idx 14.
X shape: (8, 15, 250)
Y shape: (8, 15)
Getting batch idx 15.
X shape: (2, 16, 250)
Y shape: (2, 16)
Getting batch idx 16.
X shape: (1, 17, 250)
Y shape: (1, 17)
Getting batch idx 17.
X shape: (4, 18, 250)
Y shape: (4, 18)
Getting batch idx 18.
X shape: (4, 19, 250)
Y shape: (4, 19)
Getting batch idx 19.
X shape: (2, 20, 250)
Y shape: (2, 20)
Getting batch idx 20.
X shape: (1, 21, 250)
Y shape: (1, 21)
Getting batch idx 21.
X shape: (2, 22, 250)
Y

[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]]
[[  4.46250896e-01   5.06198377e-01   4.77561404e-01   4.05091686e-01
    4.83290382e-01   8.28119339e-01   3.50327095e-01   4.55811497e-01
    4.50100754e-01   5.68454370e-01   6.21481964e-01   9.84655477e-01
    2.13299643e-01   4.55811497e-01   4.50100754e-01   4.05091686e-01
    4.68125494e-01   5.15516493e-01   2.12069805e-09   1.25025979e-07]
 [  5.03168501e-01   4.80411681e-01   5.63473410e-01   2.54894671e-01
    4.80411681e-01   4.80411681e-01   8.94547832e-01   5.63473410e-01
    2.54894671e-01   4.80411681e-01   1.77782577e-01   3.27178320e-12
    5.35537105e-01   4.

X shape: (16, 7, 250)
Y shape: (16, 7)
Getting batch idx 7.
X shape: (13, 8, 250)
Y shape: (13, 8)
Getting batch idx 8.
X shape: (12, 9, 250)
Y shape: (12, 9)
Getting batch idx 9.
X shape: (6, 10, 250)
Y shape: (6, 10)
Getting batch idx 10.
X shape: (13, 11, 250)
Y shape: (13, 11)
Getting batch idx 11.
X shape: (6, 12, 250)
Y shape: (6, 12)
Getting batch idx 12.
X shape: (10, 13, 250)
Y shape: (10, 13)
Getting batch idx 13.
X shape: (9, 14, 250)
Y shape: (9, 14)
Getting batch idx 14.
X shape: (8, 15, 250)
Y shape: (8, 15)
Getting batch idx 15.
X shape: (2, 16, 250)
Y shape: (2, 16)
Getting batch idx 16.
X shape: (1, 17, 250)
Y shape: (1, 17)
Getting batch idx 17.
X shape: (4, 18, 250)
Y shape: (4, 18)
Getting batch idx 18.
X shape: (4, 19, 250)
Y shape: (4, 19)
Getting batch idx 19.
X shape: (2, 20, 250)
Y shape: (2, 20)
Getting batch idx 20.
X shape: (1, 21, 250)
Y shape: (1, 21)
Getting batch idx 21.
X shape: (2, 22, 250)
Y shape: (2, 22)
Getting batch idx 22.
X shape: (4, 23, 250)
Y

[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 ..., 
 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  


Getting batch idx 25.
X shape: (1, 30, 250)
Y shape: (1, 30)
Getting batch idx 26.
X shape: (1, 33, 250)
Y shape: (1, 33)
Getting batch idx 27.
X shape: (1, 34, 250)
Y shape: (1, 34)
Getting batch idx 28.
X shape: (1, 35, 250)
Y shape: (1, 35)
Getting batch idx 29.
X shape: (1, 40, 250)
Y shape: (1, 40)
Getting batch idx 30.
Getting batch idx 0.
X shape: (40, 1, 250)
Y shape: (40, 1)
Getting batch idx 1.
X shape: (34, 2, 250)
Y shape: (34, 2)
Getting batch idx 2.
X shape: (31, 3, 250)
Y shape: (31, 3)
Getting batch idx 3.
X shape: (27, 4, 250)
Y shape: (27, 4)
Getting batch idx 4.
X shape: (23, 5, 250)
Y shape: (23, 5)
Getting batch idx 5.
X shape: (15, 6, 250)
Y shape: (15, 6)
Getting batch idx 6.
X shape: (16, 7, 250)
Y shape: (16, 7)
Getting batch idx 7.
X shape: (13, 8, 250)
Y shape: (13, 8)
Getting batch idx 8.
X shape: (12, 9, 250)
Y shape: (12, 9)
Getting batch idx 9.
X shape: (6, 10, 250)
Y shape: (6, 10)
Getting batch idx 10.
X shape: (13, 11, 250)
Y shape: (13, 11)
Getting b

[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 ..., 
 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  

Getting batch idx 24.
X shape: (2, 26, 250)
Y shape: (2, 26)
Getting batch idx 25.
X shape: (1, 30, 250)
Y shape: (1, 30)
Getting batch idx 26.
X shape: (1, 33, 250)
Y shape: (1, 33)
Getting batch idx 27.
X shape: (1, 34, 250)
Y shape: (1, 34)
Getting batch idx 28.
X shape: (1, 35, 250)
Y shape: (1, 35)
Getting batch idx 29.
X shape: (1, 40, 250)
Y shape: (1, 40)
Getting batch idx 30.
Getting batch idx 0.
X shape: (40, 1, 250)
Y shape: (40, 1)
Getting batch idx 1.
X shape: (34, 2, 250)
Y shape: (34, 2)
Getting batch idx 2.
X shape: (31, 3, 250)
Y shape: (31, 3)
Getting batch idx 3.
X shape: (27, 4, 250)
Y shape: (27, 4)
Getting batch idx 4.
X shape: (23, 5, 250)
Y shape: (23, 5)
Getting batch idx 5.
X shape: (15, 6, 250)
Y shape: (15, 6)
Getting batch idx 6.
X shape: (16, 7, 250)
Y shape: (16, 7)
Getting batch idx 7.
X shape: (13, 8, 250)
Y shape: (13, 8)
Getting batch idx 8.
X shape: (12, 9, 250)
Y shape: (12, 9)
Getting batch idx 9.
X shape: (6, 10, 250)
Y shape: (6, 10)
Getting batc


[[[ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]]

 ..., 
 [[ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]]]
[[ 0.5137191 ]
 [ 0.5137191 ]
 [ 0.5647695 ]
 [ 0.44514291]
 [ 0.44028732]
 [ 0.38828752]
 [ 0.47564182]
 [ 0.71831793]
 [ 0.58049927]
 [ 0.52894132]
 [ 0.52894132]
 [ 0.45475994]
 [ 0.597051  ]
 [ 0.52220411]
 [ 0.48243448]
 [ 0.74770382]
 [ 0.51527117]
 [ 0.60047067]
 [ 0.57118331]
 [ 0.5725783 ]
 [ 0.54496885]
 [ 0.47222936]
 [ 0.9981083 ]
 [ 0.56881635]
 [ 0.51571733]
 [ 0.99950667]
 [ 0.60098745]
 [ 0.58072271]
 [ 0.68307409]
 [ 0.41307047]
 [ 0.53400748]
 [ 0.56109571]
 [ 0.48225267]
 [ 0.5240197 ]
 [ 0.50188718]
 [ 0.35394939]
 [ 0.76189011]
 [ 0.55248304]
 [ 0.44252374]
 [ 0.49666817]]
[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  

Getting batch idx 10.
X shape: (13, 11, 250)
Y shape: (13, 11)
Getting batch idx 11.
X shape: (6, 12, 250)
Y shape: (6, 12)
Getting batch idx 12.
X shape: (10, 13, 250)
Y shape: (10, 13)
Getting batch idx 13.
X shape: (9, 14, 250)
Y shape: (9, 14)
Getting batch idx 14.
X shape: (8, 15, 250)
Y shape: (8, 15)
Getting batch idx 15.
X shape: (2, 16, 250)
Y shape: (2, 16)
Getting batch idx 16.
X shape: (1, 17, 250)
Y shape: (1, 17)
Getting batch idx 17.
X shape: (4, 18, 250)
Y shape: (4, 18)
Getting batch idx 18.
X shape: (4, 19, 250)
Y shape: (4, 19)
Getting batch idx 19.
X shape: (2, 20, 250)
Y shape: (2, 20)
Getting batch idx 20.
X shape: (1, 21, 250)
Y shape: (1, 21)
Getting batch idx 21.
X shape: (2, 22, 250)
Y shape: (2, 22)
Getting batch idx 22.
X shape: (4, 23, 250)
Y shape: (4, 23)
Getting batch idx 23.
X shape: (1, 24, 250)
Y shape: (1, 24)
Getting batch idx 24.
X shape: (2, 26, 250)
Y shape: (2, 26)
Getting batch idx 25.
X shape: (1, 30, 250)
Y shape: (1, 30)
Getting batch idx 26


[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]]
[[  4.46250896e-01   5.06198377e-01   4.77561404e-01   4.05091686e-01
    4.83290382e-01   8.28119339e-01   3.50327095e-01   4.55811497e-01
    4.50100754e-01   5.68454370e-01   6.21481964e-01   9.84655477e-01
    2.13299643e-01   4.55811497e-01   4.50100754e-01   4.05091686e-01
    4.68125494e-01   5.15516493e-01   2.12069805e-09   1.25025979e-07]
 [  5.03168501e-01   4.80411681e-01   5.63473410e-01   2.54894671e-01
    4.80411681e-01   4.80411681e-01   8.94547832e-01   5.63473410e-01
    2.54894671e-01   4.80411681e-01   1.77782577e-01   3.27178320e-12
    5.35537105e-01   4

Getting batch idx 6.
X shape: (16, 7, 250)
Y shape: (16, 7)
Getting batch idx 7.
X shape: (13, 8, 250)
Y shape: (13, 8)
Getting batch idx 8.
X shape: (12, 9, 250)
Y shape: (12, 9)
Getting batch idx 9.
X shape: (6, 10, 250)
Y shape: (6, 10)
Getting batch idx 10.
X shape: (13, 11, 250)
Y shape: (13, 11)
Getting batch idx 11.
X shape: (6, 12, 250)
Y shape: (6, 12)
Getting batch idx 12.
X shape: (10, 13, 250)
Y shape: (10, 13)
Getting batch idx 13.
X shape: (9, 14, 250)
Y shape: (9, 14)
Getting batch idx 14.
X shape: (8, 15, 250)
Y shape: (8, 15)
Getting batch idx 15.
X shape: (2, 16, 250)
Y shape: (2, 16)
Getting batch idx 16.
X shape: (1, 17, 250)
Y shape: (1, 17)
Getting batch idx 17.
X shape: (4, 18, 250)
Y shape: (4, 18)
Getting batch idx 18.
X shape: (4, 19, 250)
Y shape: (4, 19)
Getting batch idx 19.
X shape: (2, 20, 250)
Y shape: (2, 20)
Getting batch idx 20.
X shape: (1, 21, 250)
Y shape: (1, 21)
Getting batch idx 21.
X shape: (2, 22, 250)
Y shape: (2, 22)
Getting batch idx 22.
X 

[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 ..., 
 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  

Getting batch idx 18.
X shape: (4, 19, 250)
Y shape: (4, 19)
Getting batch idx 19.
X shape: (2, 20, 250)
Y shape: (2, 20)
Getting batch idx 20.
X shape: (1, 21, 250)
Y shape: (1, 21)
Getting batch idx 21.
X shape: (2, 22, 250)
Y shape: (2, 22)
Getting batch idx 22.
X shape: (4, 23, 250)
Y shape: (4, 23)
Getting batch idx 23.
X shape: (1, 24, 250)
Y shape: (1, 24)
Getting batch idx 24.
X shape: (2, 26, 250)
Y shape: (2, 26)
Getting batch idx 25.
X shape: (1, 30, 250)
Y shape: (1, 30)
Getting batch idx 26.
X shape: (1, 33, 250)
Y shape: (1, 33)
Getting batch idx 27.
X shape: (1, 34, 250)
Y shape: (1, 34)
Getting batch idx 28.
X shape: (1, 35, 250)
Y shape: (1, 35)
Getting batch idx 29.
X shape: (1, 40, 250)
Y shape: (1, 40)
Getting batch idx 30.
Getting batch idx 0.
X shape: (40, 1, 250)
Y shape: (40, 1)
Getting batch idx 1.
X shape: (34, 2, 250)
Y shape: (34, 2)
Getting batch idx 2.
X shape: (31, 3, 250)
Y shape: (31, 3)
Getting batch idx 3.
X shape: (27, 4, 250)
Y shape: (27, 4)
Gettin


[[  4.27258367e-01   4.44054508e-01   4.52306699e-01   7.10480060e-01
    6.55547628e-01   9.53804318e-01]
 [  4.41142271e-01   4.63235230e-01   4.63825564e-01   7.29671192e-01
    6.50344546e-01   9.64395859e-01]
 [  5.28941319e-01   5.79425279e-01   9.35325439e-01   7.84301028e-01
    4.76064320e-01   9.92150921e-11]
 [  6.61465781e-01   5.81352844e-01   4.81867235e-01   4.48175468e-01
    5.65083951e-01   8.78805398e-10]
 [  4.60150787e-01   4.80350943e-01   4.04274331e-01   6.65918812e-01
    4.19245283e-01   9.37877631e-01]
 [  5.17321198e-01   6.94782302e-01   1.25166550e-01   4.22451428e-01
    5.17321198e-01   6.44915433e-01]
 [  5.25573730e-01   6.78853142e-15   8.53325022e-01   8.38902280e-01
    6.41672335e-01   6.61358284e-01]
 [  5.48097502e-01   4.25330617e-25   8.73585012e-01   9.23687128e-01
    5.48097502e-01   9.38715357e-01]
 [  4.82162571e-01   7.92331016e-01   9.95312621e-01   4.52640787e-08
    4.67855733e-01   4.56124314e-01]
 [  5.14516549e-01   9.77187755e-01 

Getting batch idx 14.
X shape: (8, 15, 250)
Y shape: (8, 15)
Getting batch idx 15.
X shape: (2, 16, 250)
Y shape: (2, 16)
Getting batch idx 16.
X shape: (1, 17, 250)
Y shape: (1, 17)
Getting batch idx 17.
X shape: (4, 18, 250)
Y shape: (4, 18)
Getting batch idx 18.
X shape: (4, 19, 250)
Y shape: (4, 19)
Getting batch idx 19.
X shape: (2, 20, 250)
Y shape: (2, 20)
Getting batch idx 20.
X shape: (1, 21, 250)
Y shape: (1, 21)
Getting batch idx 21.
X shape: (2, 22, 250)
Y shape: (2, 22)
Getting batch idx 22.
X shape: (4, 23, 250)
Y shape: (4, 23)
Getting batch idx 23.
X shape: (1, 24, 250)
Y shape: (1, 24)
Getting batch idx 24.
X shape: (2, 26, 250)
Y shape: (2, 26)
Getting batch idx 25.
X shape: (1, 30, 250)
Y shape: (1, 30)
Getting batch idx 26.
X shape: (1, 33, 250)
Y shape: (1, 33)
Getting batch idx 27.
X shape: (1, 34, 250)
Y shape: (1, 34)
Getting batch idx 28.
X shape: (1, 35, 250)
Y shape: (1, 35)
Getting batch idx 29.
X shape: (1, 40, 250)
Y shape: (1, 40)
Getting batch idx 30.
Ge

[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]]
[[  4.75565443e-01   4.75390093e-01   8.60713849e-02   3.28937890e-09
    8.01233885e-01   4.55396704e-01   8.01233885e-01   2.33502558e-01
    7.60492902e-01   4.75565443e-01   4.75390093e-01   8.60713849e-02
    8.01233885e-01   2.55062801e-01   4.55396704e-01   8.01233885e-01]
 [  1.68212254e-01   2.07008754e-01   4.65758371e-01   7.21284789e-01
    9.44549919e-01   7.44790601e-02   4.33047721e-01   7.46101433e-01
    7.67218564e-01   4.65758371e-01   6.82528545e-01   3.58856931e-01
    1.30804936e-10   3.87184605e-01   4.65758371e-01   6.47305226e-01]]
[[[ 0.  0.  0. ...,  

Getting batch idx 4.
X shape: (23, 5, 250)
Y shape: (23, 5)
Getting batch idx 5.
X shape: (15, 6, 250)
Y shape: (15, 6)
Getting batch idx 6.
X shape: (16, 7, 250)
Y shape: (16, 7)
Getting batch idx 7.
X shape: (13, 8, 250)
Y shape: (13, 8)
Getting batch idx 8.
X shape: (12, 9, 250)
Y shape: (12, 9)
Getting batch idx 9.
X shape: (6, 10, 250)
Y shape: (6, 10)
Getting batch idx 10.
X shape: (13, 11, 250)
Y shape: (13, 11)
Getting batch idx 11.
X shape: (6, 12, 250)
Y shape: (6, 12)
Getting batch idx 12.
X shape: (10, 13, 250)
Y shape: (10, 13)
Getting batch idx 13.
X shape: (9, 14, 250)
Y shape: (9, 14)
Getting batch idx 14.
X shape: (8, 15, 250)
Y shape: (8, 15)
Getting batch idx 15.
X shape: (2, 16, 250)
Y shape: (2, 16)
Getting batch idx 16.
X shape: (1, 17, 250)
Y shape: (1, 17)
Getting batch idx 17.
X shape: (4, 18, 250)
Y shape: (4, 18)
Getting batch idx 18.
X shape: (4, 19, 250)
Y shape: (4, 19)
Getting batch idx 19.
X shape: (2, 20, 250)
Y shape: (2, 20)
Getting batch idx 20.
X sh

[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 ..., 
 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  1. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  

Getting batch idx 25.
X shape: (1, 30, 250)
Y shape: (1, 30)
Getting batch idx 26.
X shape: (1, 33, 250)
Y shape: (1, 33)
Getting batch idx 27.
X shape: (1, 34, 250)
Y shape: (1, 34)
Getting batch idx 28.
X shape: (1, 35, 250)
Y shape: (1, 35)
Getting batch idx 29.
X shape: (1, 40, 250)
Y shape: (1, 40)
Getting batch idx 30.
Getting batch idx 0.
X shape: (40, 1, 250)
Y shape: (40, 1)
Getting batch idx 1.
X shape: (34, 2, 250)
Y shape: (34, 2)
Getting batch idx 2.
X shape: (31, 3, 250)
Y shape: (31, 3)
Getting batch idx 3.
X shape: (27, 4, 250)
Y shape: (27, 4)
Getting batch idx 4.
X shape: (23, 5, 250)
Y shape: (23, 5)
Getting batch idx 5.
X shape: (15, 6, 250)
Y shape: (15, 6)
Getting batch idx 6.
X shape: (16, 7, 250)
Y shape: (16, 7)
Getting batch idx 7.
X shape: (13, 8, 250)
Y shape: (13, 8)
Getting batch idx 8.
X shape: (12, 9, 250)
Y shape: (12, 9)
Getting batch idx 9.
X shape: (6, 10, 250)
Y shape: (6, 10)
Getting batch idx 10.
X shape: (13, 11, 250)
Y shape: (13, 11)
Getting ba


[[  4.80182071e-01   4.63707334e-01   4.86176351e-01   6.59745331e-01
    5.65911737e-01   4.86176351e-01   8.13125244e-02]
 [  4.32053882e-01   4.55494226e-01   4.71513972e-01   4.83480753e-01
    6.38685347e-01   6.62242476e-01   9.25754605e-01]
 [  3.29337236e-01   4.26283785e-01   7.58757578e-01   8.21363533e-01
    4.26283785e-01   8.51784065e-01   8.21363533e-01]
 [  4.22967226e-01   4.35267921e-01   5.24409102e-01   4.50824018e-01
    9.35971457e-01   4.50824018e-01   6.64303827e-01]
 [  5.00161184e-01   4.14952181e-01   3.79360579e-01   2.53914244e-01
    2.54333479e-01   5.07458433e-01   4.98352098e-01]
 [  4.50028094e-01   5.37052571e-01   6.23672872e-01   3.49859567e-01
    4.13896835e-01   7.55355619e-01   0.00000000e+00]
 [  4.75489919e-01   7.40345487e-01   7.68149887e-01   5.60813800e-01
    5.37151653e-01   4.75489919e-01   6.26318244e-01]
 [  4.61182679e-01   4.37469880e-01   4.37469880e-01   3.15349535e-15
    4.61182679e-01   8.68055909e-01   5.35297113e-01]
 [  4.8

X shape: (4, 18, 250)
Y shape: (4, 18)
Getting batch idx 18.
X shape: (4, 19, 250)
Y shape: (4, 19)
Getting batch idx 19.
X shape: (2, 20, 250)
Y shape: (2, 20)
Getting batch idx 20.
X shape: (1, 21, 250)
Y shape: (1, 21)
Getting batch idx 21.
X shape: (2, 22, 250)
Y shape: (2, 22)
Getting batch idx 22.
X shape: (4, 23, 250)
Y shape: (4, 23)
Getting batch idx 23.
X shape: (1, 24, 250)
Y shape: (1, 24)
Getting batch idx 24.
X shape: (2, 26, 250)
Y shape: (2, 26)
Getting batch idx 25.
X shape: (1, 30, 250)
Y shape: (1, 30)
Getting batch idx 26.
X shape: (1, 33, 250)
Y shape: (1, 33)
Getting batch idx 27.
X shape: (1, 34, 250)
Y shape: (1, 34)
Getting batch idx 28.
X shape: (1, 35, 250)
Y shape: (1, 35)
Getting batch idx 29.
X shape: (1, 40, 250)
Y shape: (1, 40)
Getting batch idx 30.
Getting batch idx 0.
X shape: (40, 1, 250)
Y shape: (40, 1)
Getting batch idx 1.
X shape: (34, 2, 250)
Y shape: (34, 2)
Getting batch idx 2.
X shape: (31, 3, 250)
Y shape: (31, 3)
Getting batch idx 3.
X shap

[[[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 ..., 
 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]

 [[ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]
  [ 0.  0.  0. ...,  0.  0.  1.]]]
[[  6.29178798e-001   4.48419794e-001   4.90061338e-001   3.47877611e-015]
 [  4.47614774e-001   4.84389616e-001   5.74961554e-001   6.79124512e-001]
 [  5.97050998e-001   4.67139113e-001  

X shape: (13, 8, 250)
Y shape: (13, 8)
Getting batch idx 8.
X shape: (12, 9, 250)
Y shape: (12, 9)
Getting batch idx 9.
X shape: (6, 10, 250)
Y shape: (6, 10)
Getting batch idx 10.
X shape: (13, 11, 250)
Y shape: (13, 11)
Getting batch idx 11.
X shape: (6, 12, 250)
Y shape: (6, 12)
Getting batch idx 12.
X shape: (10, 13, 250)
Y shape: (10, 13)
Getting batch idx 13.
X shape: (9, 14, 250)
Y shape: (9, 14)
Getting batch idx 14.
X shape: (8, 15, 250)
Y shape: (8, 15)
Getting batch idx 15.
X shape: (2, 16, 250)
Y shape: (2, 16)
Getting batch idx 16.
X shape: (1, 17, 250)
Y shape: (1, 17)
Getting batch idx 17.
X shape: (4, 18, 250)
Y shape: (4, 18)
Getting batch idx 18.
X shape: (4, 19, 250)
Y shape: (4, 19)
Getting batch idx 19.
X shape: (2, 20, 250)
Y shape: (2, 20)
Getting batch idx 20.
X shape: (1, 21, 250)
Y shape: (1, 21)
Getting batch idx 21.
X shape: (2, 22, 250)
Y shape: (2, 22)
Getting batch idx 22.
X shape: (4, 23, 250)
Y shape: (4, 23)
Getting batch idx 23.
X shape: (1, 24, 250)


ValueError: Error when checking target: expected dense_18 to have shape (None, 1) but got array with shape (10, 13)

In [9]:
import matplotlib.pyplot as plt

# https://machinelearningmastery.com/display-deep-learning-model-training-history-in-keras/

# list all data in history
#print(training_history.history.keys())
# summarize history for accuracy
plt.plot(training_history.history['acc'])
plt.plot(training_history.history['val_acc'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()
# summarize history for loss
plt.plot(training_history.history['loss'])
plt.plot(training_history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

In [28]:
# test LSTM

import logging

def onehot_encodings(features : np.ndarray, onehot_encoder) -> np.ndarray:
    """
    :param features: A 2D array of feature vectors, each of which starts with one-hot encoding features. Any other features follow those.
    :param onehot_encoder: The instance used to encode the original values.
    :return: A 2D numpy array consisting only of one-hot encoding features.
    """
    feature_count = onehot_encoder.n_values_[0]
    return features[:,:feature_count + 1]

def onehot_encoded_word(onehot_encodings : np.ndarray, label_encoder) -> str:
    # Check if there are any non-zero values
    if onehot_encodings.any():
        word_label = onehot_encodings.argmax()
        result = label_encoder.inverse_transform([word_label])[0]
    else:
        result = "(padding)"
    return result

def word(features : np.ndarray, label_encoder, onehot_encoder) -> str:
    feature_count = onehot_encoder.n_values_[0]
    onehot = features[:feature_count + 1]
    return onehot_encoded_word(onehot, label_encoder)

def word_seq(x : np.ndarray, label_encoder, onehot_encoder) -> np.ndarray:
    word_features = onehot_encodings(x, onehot_encoder)
    return np.apply_along_axis(lambda arr : onehot_encoded_word(arr, label_encoder), 1, word_features)

def create_padded_seq_matrix(group: pd.DataFrame, seq_matrix_factory):
    seq_matrices = tuple(seq_matrix_factory(group))
    print("Created a dataset composed of {} sequence(s), with a max sequence length of {}.".format(len(seq_matrices), max(m.shape[0] for m in seq_matrices)), file=sys.stderr)
    print("Padding data sequences.", file=sys.stderr)
    return keras.preprocessing.sequence.pad_sequences(seq_matrices, maxlen=None, padding='pre', truncating='pre', value=0.0)
    

def test_token_seq(token_seq_group : pd.DataFrame, seq_matrix_factory, model: Sequential, label_encoder, onehot_encoder): 
    entity_groups = token_seq_group.groupby("ENTITY", as_index=False, sort=False)
    entity_matrices = tuple(entity_groups.apply(lambda group : (group.name, seq_matrix_factory(group))))
    #for _, m in entity_matrices:
    #    y = m[:, -1]
    #    print(y) 
    
    logging.debug("Created matrices for %d entities, with a max sequence length of %d.", len(entity_matrices), max(m.shape[0] for _, m in entity_matrices))
    logging.debug("Padding entity test data sequences.")
    test_batch = keras.preprocessing.sequence.pad_sequences(tuple(m for _, m in entity_matrices), maxlen=None, padding='pre', value=0.0, dtype='int32')
    print(test_batch[:, :, :-1])
    logging.debug("Test batch shape: %s", test_batch.shape)
    test_x, test_y = split_xy(test_batch)
    
    
    for group_name, m in entity_matrices:
        m = np.expand_dims(m, axis=0)
        print(m.shape)
        x = m[:, :, :-1]
        print(x.shape)
        y = m[:, :, -1]
        print(y.shape)
        model.predict(x, verbose=0, batch_size=1)
    
    #logging.debug("Test X shape: %s", test_x.shape)
    #logging.debug("Test Y shape: %s", test_y.shape)
    # Classify all sets of datapoints for each entity as a single batch
    #entity_predicted_scores = model.predict(test_x, verbose=0)
    
    max_score = 0
    for idx in range(0, test_x.shape[0]):
        entity_id = entity_matrices[idx][0]
        # Get the scores for each entity
        entity_x = test_x[idx]
        logging.debug("Re-scoring token sequence for entity %s: %s", entity_id, word_seq(entity_x, label_encoder, onehot_encoder))
        entity_orig_scores = test_y[idx]
        for tok_idx, features in enumerate(entity_x):
            w = word(features, label_encoder, onehot_encoder)
            s = entity_orig_scores[tok_idx]
            print("{}; Orig score: {}".format(w, s))
        
        max_score = max(max_score, entity_orig_scores.argmax())
        #print(entity_orig_scores)
        orig_score = entity_orig_scores.sum()
        #predicted_scores = entity_predicted_scores[idx]
        #print(predicted_scores)
        #rescored = np.dot(entity_orig_scores, predicted_scores)
        #logging.warning("Original score: %f; New score: %f", orig_score, rescored)
                        
    print("Max score: {}".format(max_score))
            
token_seq_groups = test_df.groupby(
                ("CROSS_VALIDATION_ITER", "DYAD", "ROUND", "UTT_START_TIME", "UTT_END_TIME"),
                as_index=False, sort=False)
print("Will test {} token sequences.".format(len(token_seq_groups)), file=sys.stderr)
test_results = token_seq_groups.apply(lambda group: test_token_seq(group, seq_matrix_factory, model, label_encoder, onehot_encoder))

                        
#test_x, test_y = split_xy(test_matrix)
#print("Training X shape: {}".format(test_x.shape), file=sys.stderr)
#print("Training Y shape: {}".format(test_y.shape), file=sys.stderr)

#seq_predicted_values = model.predict(test_x, verbose=0)
#model.reset_states()
#print("result.shape = {}".format(seq_predicted_values.shape), file=sys.stderr)
#for i, tested_seq in enumerate(test_x):
#    word_features = onehot_encodings(tested_seq, onehot_encoder)
    #print("word features: {}".format(word_features))
    #print("Tested sequence: {}".format(tested_seq))
    #print("Tested sequence shape: {}".format(tested_seq.shape))
    #seq_labels = word_features.argmax(axis=1)
    #print("Inverse labels: {}".format(inverse_labels))
    #seq_words = label_encoder.inverse_transform(seq_labels)
#    seq_words = np.apply_along_axis(lambda arr : onehot_encoded_word(arr, label_encoder), 1, word_features)
    #print("Inverse word labels: {}".format(seq_words))
#    predicted_values = seq_predicted_values[i]
#    assert tested_seq.shape[:-1] == predicted_values.shape
    #assert tested_seq.shape[:-1] == actual_values.shape
    #rint("Predicted values: {}".format(predicted_values))
#    actual_values = test_y[i]
#    assert predicted_values.shape == actual_values.shape
    
#    differences = predicted_values - actual_values
#    print("[Predicted_val - Actual_val]: {}".format(differences))
    #print("Actual values: {}".format(actual_values))
	#print('X=%.1f y=%.1f, yhat=%.1f' % (seq1[i], seq1[i+1], result[i]))

[[[0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]]

 [[0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]]

 [[0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]]

 ..., 
 [[0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]]

 [[0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]]

 [[0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]]]
(1, 3, 251)
(1, 3, 250)
(1, 3)
[[[0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]]

 [[0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]]

 [[0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]]

 ..., 
 [[0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]]

 [[0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]]

 [[0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]
  [0 0 0 ..., 0 0 1]]]
(1, 3, 251)
(1, 3, 250)
(1, 3)


Will test 125 token sequences.


ValueError: Error when checking : expected lstm_1_input to have shape (None, 40, 250) but got array with shape (1, 3, 250)